import 'package:hardwares/app/app_data/item_data_model.dart';

final List<PriceListItem> marvelPriceList = [
  PriceListItem(
    itemName: 'Pipes SDR-11 (3 mtr. length)',
    itemCode: 'CPVC100',
    companyName: "Marvel",
    category: "cpvc",
    imageUrl: "assets/cpvc/1.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1/2"', rate: 0.0),
      Variant(size: '3/4"', rate: 0.0),
      Variant(size: '1"', rate: 0.0),
      Variant(size: '1-1/4"', rate: 0.0),
      Variant(size: '1-1/2"', rate: 0.0),
      Variant(size: '2"', rate: 0.0),
    ],
  ),
  PriceListItem(
    itemName: 'Pipes SDR-13.5 (3 mtr. length)',
    itemCode: 'CPVC101',
    companyName: "Marvel",
    category: "cpvc",
    imageUrl: "assets/cpvc/1.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1/2"', rate: 0.0),
      Variant(size: '3/4"', rate: 0.0),
      Variant(size: '1"', rate: 0.0),
      Variant(size: '1-1/4"', rate: 0.0),
      Variant(size: '1-1/2"', rate: 0.0),
      Variant(size: '2"', rate: 0.0),
    ],
  ),
  PriceListItem(
    itemName: 'Coupling',
    itemCode: 'CPVC102',
    companyName: "Marvel",
    category: "cpvc",
    imageUrl: "assets/cpvc/2.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1/2"', rate: 0.0),
      Variant(size: '3/4"', rate: 0.0),
      Variant(size: '1"', rate: 0.0),
      Variant(size: '1-1/4"', rate: 0.0),
      Variant(size: '1-1/2"', rate: 0.0),
      Variant(size: '2"', rate: 0.0),
    ],
  ),
  PriceListItem(
    itemName: 'Elbow 90°',
    itemCode: 'CPVC103',
    companyName: "Marvel",
    category: "cpvc",
    imageUrl: "assets/cpvc/4.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1/2"', rate: 0.0),
      Variant(size: '3/4"', rate: 0.0),
      Variant(size: '1"', rate: 0.0),
      Variant(size: '1-1/4"', rate: 0.0),
      Variant(size: '1-1/2"', rate: 0.0),
      Variant(size: '2"', rate: 0.0),
    ],
  ),
  PriceListItem(
    itemName: 'Elbow 45°',
    itemCode: 'CPVC104',
    companyName: "Marvel",
    category: "cpvc",
    imageUrl: "assets/cpvc/6.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1/2"', rate: 0.0),
      Variant(size: '3/4"', rate: 0.0),
      Variant(size: '1"', rate: 0.0),
      Variant(size: '1-1/4"', rate: 0.0),
      Variant(size: '1-1/2"', rate: 0.0),
      Variant(size: '2"', rate: 0.0),
    ],
  ),
  PriceListItem(
    itemName: 'Tee',
    itemCode: 'CPVC105',
    companyName: "Marvel",
    category: "cpvc",
    imageUrl: "assets/cpvc/5.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1/2"', rate: 0.0),
      Variant(size: '3/4"', rate: 0.0),
      Variant(size: '1"', rate: 0.0),
      Variant(size: '1-1/4"', rate: 0.0),
      Variant(size: '1-1/2"', rate: 0.0),
      Variant(size: '2"', rate: 0.0),
    ],
  ),
  PriceListItem(
    itemName: 'End Cap',
    itemCode: 'CPVC106',
    companyName: "Marvel",
    category: "cpvc",
    imageUrl: "assets/cpvc/8.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1/2"', rate: 0.0),
      Variant(size: '3/4"', rate: 0.0),
      Variant(size: '1"', rate: 0.0),
      Variant(size: '1-1/4"', rate: 0.0),
      Variant(size: '1-1/2"', rate: 0.0),
      Variant(size: '2"', rate: 0.0),
    ],
  ),
  PriceListItem(
    itemName: 'Union',
    itemCode: 'CPVC107',
    companyName: "Marvel",
    category: "cpvc",
    imageUrl: "assets/cpvc/7.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1/2"', rate: 0.0),
      Variant(size: '3/4"', rate: 0.0),
      Variant(size: '1"', rate: 0.0),
      Variant(size: '1-1/4"', rate: 0.0),
      Variant(size: '1-1/2"', rate: 0.0),
      Variant(size: '2"', rate: 0.0),
    ],
  ),

  PriceListItem(
    itemName: 'Reducer Bush',
    itemCode: 'CPVC108',
    companyName: "Marvel",
    category: "cpvc",
    imageUrl: "assets/cpvc/21.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '3/4 x 1/2', rate: 0.0),
      Variant(size: '1 x 1/2', rate: 0.0),
      Variant(size: '1 x 3/4', rate: 0.0),
      Variant(size: '1-1/4 x 1/2', rate: 0.0),
      Variant(size: '1-1/4 x 3/4', rate: 0.0),
      Variant(size: '1-1/4 x 1', rate: 0.0),
      Variant(size: '1-1/2 x 1/2', rate: 0.0),
      Variant(size: '1-1/2 x 3/4', rate: 0.0),
      Variant(size: '1-1/2 x 1', rate: 0.0),
      Variant(size: '1-1/2 x 1-1/4', rate: 0.0),
      Variant(size: '2 x 1/2', rate: 0.0),
      Variant(size: '2 x 3/4', rate: 0.0),
      Variant(size: '2 x 1', rate: 0.0),
      Variant(size: '2 x 1-1/4', rate: 0.0),
      Variant(size: '2 x 1-1/2', rate: 0.0),
    ],
  ),

  PriceListItem(
    itemName: 'Reducer Coupling',
    itemCode: 'CPVC109',
    companyName: "Marvel",
    category: "cpvc",
    imageUrl: "assets/cpvc/19.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '3/4 x 1/2', rate: 0.0),
      Variant(size: '1 x 1/2', rate: 0.0),
      Variant(size: '1 x 3/4', rate: 0.0),
      Variant(size: '1-1/4 x 1/2', rate: 0.0),
      Variant(size: '1-1/4 x 3/4', rate: 0.0),
      Variant(size: '1-1/4 x 1', rate: 0.0),
      Variant(size: '1-1/2 x 1/2', rate: 0.0),
      Variant(size: '1-1/2 x 3/4', rate: 0.0),
      Variant(size: '1-1/2 x 1', rate: 0.0),
      Variant(size: '1-1/2 x 1-1/4', rate: 0.0),
      Variant(size: '2 x 1/2', rate: 0.0),
      Variant(size: '2 x 3/4', rate: 0.0),
      Variant(size: '2 x 1', rate: 0.0),
      Variant(size: '2 x 1-1/4', rate: 0.0),
      Variant(size: '2 x 1-1/2', rate: 0.0),
    ],
  ),

  PriceListItem(
    itemName: 'Cross Tee',
    itemCode: 'CPVC110',
    companyName: "Marvel",
    category: "cpvc",
    imageUrl: "assets/cpvc/9.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1/2"', rate: 0.0),
      Variant(size: '3/4"', rate: 0.0),
      Variant(size: '1"', rate: 0.0),
    ],
  ),
  PriceListItem(
    itemName: 'Step Over Bend',
    itemCode: 'CPVC111',
    companyName: "Marvel",
    category: "cpvc",
    imageUrl: "assets/cpvc/15.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1/2"', rate: 0.0),
      Variant(size: '3/4"', rate: 0.0),
      Variant(size: '1"', rate: 0.0),
    ],
  ),
  PriceListItem(
    itemName: 'Reducer Tee',
    itemCode: 'CPVC112',
    companyName: "Marvel",
    category: "cpvc",
    imageUrl: "assets/cpvc/20.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '3/4 x 3/4 x 1/2', rate: 0.0),
      Variant(size: '1 x 1 x 1/2', rate: 0.0),
      Variant(size: '1 x 1 x 3/4', rate: 0.0),
      Variant(size: '1-1/4 x 1-1/4 x 1/2', rate: 0.0),
      Variant(size: '1-1/4 x 1-1/4 x 3/4', rate: 0.0),
      Variant(size: '1-1/4 x 1-1/4 x 1', rate: 0.0),
      Variant(size: '1-1/2 x 1-1/2 x 1/2', rate: 0.0),
      Variant(size: '1-1/2 x 1-1/2 x 3/4', rate: 0.0),
      Variant(size: '1-1/2 x 1-1/2 x 1', rate: 0.0),
      Variant(size: '1-1/2 x 1-1/2 x 1-1/4', rate: 0.0),
      Variant(size: '2 x 2 x 1/2', rate: 0.0),
      Variant(size: '2 x 2 x 3/4', rate: 0.0),
      Variant(size: '2 x 2 x 1', rate: 0.0),
      Variant(size: '2 x 2 x 1-1/4', rate: 0.0),
      Variant(size: '2 x 2 x 1-1/2', rate: 0.0),
    ],
  ),
  PriceListItem(
    itemName: 'Brass Elbow',
    itemCode: 'CPVC113',
    companyName: "Marvel",
    category: "cpvc",
    imageUrl: "assets/cpvc/22.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1/2 x 1/2', rate: 0.0),
      Variant(size: '3/4 x 1/2', rate: 0.0),
      Variant(size: '3/4 x 3/4', rate: 0.0),
      Variant(size: '1 x 1/2', rate: 0.0),
      Variant(size: '1 x 3/4', rate: 0.0),
      Variant(size: '1 x 1', rate: 0.0),
      Variant(size: '1-1/4 x 1-1/4', rate: 0.0),
    ],
  ),
  PriceListItem(
    itemName: 'Brass Triple Elbow 6"/7"',
    itemCode: 'CPVC114',
    companyName: "Marvel",
    category: "cpvc",
    imageUrl: "assets/cpvc/29.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '3/4 x 1/2 (Solvent Joint)', rate: 0.0),
      Variant(size: '3/4 x 1/2 (No Solvent )', rate: 0.0),
    ],
  ),
  PriceListItem(
    itemName: 'Brass Double Elbow 6.5"',
    itemCode: 'CPVC115',
    companyName: "Marvel",
    category: "cpvc",
    imageUrl: "assets/cpvc/30.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '3/4 x 1/2', rate: 0.0),
    ],
  ),
  PriceListItem(
    itemName: 'Brass Reducer Elbow Male',
    itemCode: 'CPVC116',
    companyName: "Marvel",
    category: "cpvc",
    imageUrl: "assets/cpvc/41.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '3/4 x 1/2', rate: 0.0),
    ],
  ),
  PriceListItem(
    itemName: 'Brass Tee',
    itemCode: 'CPVC117',
    companyName: "Marvel",
    category: "cpvc",
    imageUrl: "assets/cpvc/23.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1/2 x 1/2 x 1/2', rate: 0.0),
      Variant(size: '3/4 x 3/4 x 1/2', rate: 0.0),
      Variant(size: '3/4 x 3/4 x 3/4', rate: 0.0),
      Variant(size: '1 x 1 x 1', rate: 0.0),
      Variant(size: '1 x 1 x 1/2', rate: 0.0),
      Variant(size: '1 x 1 x 3/4', rate: 0.0),
      Variant(size: '1-1/4 x 1-1/4 x 1-1/4', rate: 0.0),
      Variant(size: '1-1/4 x 1-1/4 x 1/2', rate: 0.0),
      Variant(size: '1-1/4 x 1-1/4 x 3/4', rate: 0.0),
      Variant(size: '1-1/4 x 1-1/4 x 1', rate: 0.0),
    ],
  ),
  PriceListItem(
    itemName: 'Brass Reducer Tee Male',
    itemCode: 'CPVC118',
    companyName: "Marvel",
    category: "cpvc",
    imageUrl: "assets/cpvc/40.jpg",
    isCompanyItems: true,
    variants: [
      Variant(size: '1 x 1 x 1/2', rate: 0.0),
    ],
  ),
  PriceListItem(
    itemName: 'Brass Reducer Coupling',
    itemCode: 'CPVC119',
    companyName: "Marvel",
    category: "cpvc",
    imageUrl: "assets/cpvc/24.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '3/4 x 1/2', rate: 0.0),
      Variant(size: '1 x 1/2', rate: 0.0),
      Variant(size: '1 x 3/4', rate: 0.0),
    ],
  ),
  PriceListItem(
    itemName: 'Brass Male Adapter',
    itemCode: 'CPVC120',
    companyName: "Marvel",
    category: "cpvc",
    imageUrl: "assets/cpvc/28.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1/2"', rate: 0.0),
      Variant(size: '3/4"', rate: 0.0),
      Variant(size: '1"', rate: 0.0),
      Variant(size: '1-1/4"', rate: 0.0),
      Variant(size: '1-1/2"', rate: 0.0),
      Variant(size: '2"', rate: 0.0),
      Variant(size: '3/4 x 1/2', rate: 0.0),
      Variant(size: '1 x 1/2', rate: 0.0),
    ],
  ),
  PriceListItem(
    itemName: 'Brass Female Adapter',
    itemCode: 'CPVC121',
    companyName: "Marvel",
    category: "cpvc",
    imageUrl: "assets/cpvc/27.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1/2"', rate: 0.0),
      Variant(size: '3/4"', rate: 0.0),
      Variant(size: '1"', rate: 0.0),
      Variant(size: '1-1/4"', rate: 0.0),
      Variant(size: '1-1/2"', rate: 0.0),
      Variant(size: '2"', rate: 0.0),
    ],
  ),
  PriceListItem(
    itemName: 'Tank Adapter (Threaded Type)',
    itemCode: 'CPVC122',
    companyName: "Marvel",
    category: "cpvc",
    imageUrl: "assets/cpvc/10.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1/2"', rate: 0.0),
      Variant(size: '3/4"', rate: 0.0),
      Variant(size: '1"', rate: 0.0),
      Variant(size: '1-1/4"', rate: 0.0),
      Variant(size: '1-1/2"', rate: 0.0),
      Variant(size: '2"', rate: 0.0),
    ],
  ),

  PriceListItem(
    itemName: 'Tank Adapter (Push Type)',
    itemCode: 'CPVC123',
    companyName: "Marvel",
    category: "cpvc",
    imageUrl: "assets/cpvc/10.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1"', rate: 0.0),
      Variant(size: '1-1/4"', rate: 0.0),
      Variant(size: '1-1/2"', rate: 0.0),
      Variant(size: '2"', rate: 0.0),
    ],
  ),
  PriceListItem(
    itemName: 'Transition Bush (IPS/CTS)',
    itemCode: 'CPVC124',
    companyName: "Marvel",
    category: "cpvc",
    imageUrl: "assets/cpvc/34.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1/2 IPS x 1/2 CTS', rate: 0.0),
      Variant(size: '3/4 IPS x 3/4 CTS', rate: 0.0),
      Variant(size: '1 IPS x 1 CTS', rate: 0.0),
      Variant(size: '1-1/4 IPS x 1-1/4 CTS', rate: 0.0),
      Variant(size: '1-1/2 IPS x 1-1/2 CTS', rate: 0.0),
      Variant(size: '2 IPS x 2 CTS', rate: 0.0),
    ],
  ),
  PriceListItem(
    itemName: 'Long Radius 90° Bend',
    itemCode: 'CPVC125',
    companyName: "Marvel",
    category: "cpvc",
    imageUrl: "assets/cpvc/35.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '3/4"', rate: 0.0),
      Variant(size: '1"', rate: 0.0),
      Variant(size: '1-1/4"', rate: 0.0),
      Variant(size: '1-1/2"', rate: 0.0),
      Variant(size: '2"', rate: 0.0),
    ],
  ),
  PriceListItem(
    itemName: 'Metal Strap C Type (Powder Coated)',
    itemCode: 'CPVC126',
    companyName: "Marvel",
    category: "cpvc",
    imageUrl: "assets/cpvc/3.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1/2"', rate: 0.0),
      Variant(size: '3/4"', rate: 0.0),
      Variant(size: '1"', rate: 0.0),
      Variant(size: '1-1/4"', rate: 0.0),
      Variant(size: '1-1/2"', rate: 0.0),
      Variant(size: '2"', rate: 0.0),
    ],
  ),
  PriceListItem(
    itemName: 'SPLIT CLAMP WITH GASKET',
    itemCode: 'CPVC127',
    companyName: "Marvel",
    category: "cpvc",
    imageUrl: "assets/cpvc/36.jpg",
    isCompanyItems: true,
    variants: [
      Variant(size: '3/4"', rate: 0.0),
      Variant(size: '1"', rate: 0.0),
      Variant(size: '1-1/4"', rate: 0.0),
      Variant(size: '1-1/2"', rate: 0.0),
      Variant(size: '2"', rate: 0.0),
    ],
  ),
  PriceListItem(
    itemName: 'DOUBLE NAIL CLAMP',
    itemCode: 'CPVC128',
    companyName: "Marvel",
    category: "cpvc",
    imageUrl: "assets/cpvc/37.jpg",
    isCompanyItems: true,
    variants: [
      Variant(size: '3/4"', rate: 0.0),
      Variant(size: '1"', rate: 0.0),
    ],
  ),
  PriceListItem(
    itemName: 'REDUCER ELBOW',
    itemCode: 'CPVC129',
    companyName: "Marvel",
    category: "cpvc",
    imageUrl: "assets/cpvc/25.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '3/4" x 1/2"', rate: 0.0),
    ],
  ),
  PriceListItem(
    itemName: 'MALE ADAPTER(CPVC THREADS)',
    itemCode: 'CPVC130',
    companyName: "Marvel",
    category: "cpvc",
    imageUrl: "assets/cpvc/12.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1/2"', rate: 0.0),
      Variant(size: '3/4"', rate: 0.0),
      Variant(size: '1"', rate: 0.0),
      Variant(size: '1-1/4"', rate: 0.0),
      Variant(size: '1-1/2"', rate: 0.0),
      Variant(size: '2"', rate: 0.0),
      Variant(size: '3/4Soc x 1/2 MIP"', rate: 0.0),
    ],
  ),
  PriceListItem(
    itemName: 'FEMALE ADAPTER(CPVC THREADS)',
    itemCode: 'CPVC131',
    companyName: "Marvel",
    category: "cpvc",
    imageUrl: "assets/cpvc/11.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1/2"', rate: 0.0),
      Variant(size: '3/4"', rate: 0.0),
      Variant(size: '1"', rate: 0.0),
      Variant(size: '1-1/4"', rate: 0.0),
      Variant(size: '1-1/2"', rate: 0.0),
      Variant(size: '2"', rate: 0.0),
    ],
  ),
  PriceListItem(
    itemName: 'Adhesive solution (E-Z weld) Flow Guard Gold (yellow)',
    itemCode: 'CPVC132',
    companyName: "Marvel",
    category: "cpvc",
    imageUrl: "assets/cpvc/38.jpg",
    isCompanyItems: true,
    variants: [
      Variant(size: '29.5 ml(tube)', rate: 0.0),
      Variant(size: '59 ml (tin)', rate: 0.0),
      Variant(size: '118 ml (tin)', rate: 0.0),
      Variant(size: '237 ml (Tin)', rate: 0.0),
    ],
  ),
  PriceListItem(
    itemName: 'Ball valve (Spears, USA, Commercial-Heavy)',
    itemCode: 'CPVC133',
    companyName: "Marvel",
    category: "cpvc",
    imageUrl: "assets/cpvc/14.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1/2"', rate: 0.0),
      Variant(size: '3/4"', rate: 0.0),
      Variant(size: '1"', rate: 0.0),
      Variant(size: '1-1/4"', rate: 0.0),
      Variant(size: '1-1/2"', rate: 0.0),
      Variant(size: '2"', rate: 0.0),
    ],
  ),
  PriceListItem(
    itemName: 'Ball valve (Ashirvad)',
    itemCode: 'CPVC134',
    companyName: "Marvel",
    category: "cpvc",
    imageUrl: "assets/cpvc/39.jpg",
    isCompanyItems: true,
    variants: [
      Variant(size: '1/2"', rate: 0.0),
      Variant(size: '3/4"', rate: 0.0),
      Variant(size: '1"', rate: 0.0),
      Variant(size: '1-1/4"', rate: 0.0),
      Variant(size: '1-1/2"', rate: 0.0),
      Variant(size: '2"', rate: 0.0),
    ],
  ),

//----------------  upvc ------------------------
// ------------------------------------------------------------------
// ------------------------------------------------------------------

// Marvel UPVC Items - Sorted to match Nepatop order with same item codes

// 1. Socket (coupler) - matches Nepatop UPVC101
  PriceListItem(
    itemName: 'Marvel Aquaflo uPVC Pipes  (Grey colour)',
    itemCode: 'MAR001',
    companyName: "Marvel",
    category: "upvc",
    imageUrl: "assets/upvc/aquaflow.jpg",
    unit: "pice",
    subType: 'pipe',
    isCompanyItems: true,
    variants: [
      Variant(size: 'Plain Socket 3 mtrs  (2.5 Kg/cm2)', rate: 0.0),
      Variant(size: 'Plain Socket 6 mtrs  (2.5 Kg/cm2)', rate: 0.0),
      Variant(size: 'Plain Socket 3 mtrs  (4 Kg/cm2)', rate: 0.0),
      Variant(size: 'Plain Socket 6 mtrs  (4 Kg/cm2)', rate: 0.0),
      Variant(size: 'Plain Socket 3 mtrs  (6 Kg/cm2)', rate: 0.0),
      Variant(size: 'Plain Socket 6 mtrs  (6 Kg/cm2)', rate: 0.0),
      Variant(size: 'Plain Socket 3 mtrs  (10 Kg/cm2)', rate: 0.0),
      Variant(size: 'Plain Socket 6 mtrs  (10 Kg/cm2)', rate: 0.0),
    ],
  ),

  PriceListItem(
    itemName: 'EcoDrain   (Grey colour)',
    itemCode: 'MAR0001',
    companyName: "Marvel",
    category: "upvc",
    imageUrl: "assets/upvc/aquaflow.jpg",
    unit: "pice",
    subType: 'pipe',
    isCompanyItems: true,
    variants: [
      Variant(size: 'Single Socket (R/R) 3mtrs (Type A)', rate: 0.0),
      Variant(size: 'Double  Socket(R/R) 3mtrs (Type A)  ', rate: 0.0),
      Variant(size: 'Single Socket (R/R) 3mtrs (Type B)', rate: 0.0),
      Variant(size: 'Double  Socket(R/R) 3mtrs (Type B)  ', rate: 0.0),
      Variant(size: 'Plain Socket 3 mtrs  (Type A)', rate: 0.0),
      Variant(size: 'Plain Socket 6 mtrs  (Type A)', rate: 0.0),
      Variant(size: 'Plain Socket 3 mtrs  (Type B)', rate: 0.0),
      Variant(size: 'Plain Socket 6 mtrs  (Type B)', rate: 0.0),
    ],
  ),

  PriceListItem(
    itemName: 'Marvel Duradrain  (Golder Brown Colour)',
    itemCode: 'MAR001',
    companyName: "Marvel",
    category: "upvc",
    imageUrl: "assets/upvc/Marvel_Duradrain_Pvc.jpg",
    unit: "pice",
    subType: 'pipe',
    isCompanyItems: true,
    variants: [
      Variant(size: 'Plain Socket 3 mtrs (SN 2)', rate: 0.0),
      Variant(size: 'Plain Socket 6 mtrs (SN 2)', rate: 0.0),
      Variant(size: 'Plain Socket 3 mtrs (SN 4)', rate: 0.0),
      Variant(size: 'Plain Socket 6 mtrs (SN 4)', rate: 0.0),
      Variant(size: 'Plain Socket 3 mtrs (SN 8)', rate: 0.0),
      Variant(size: 'Plain Socket 6 mtrs (SN 8)', rate: 0.0),
    ],
  ),
  PriceListItem(
    itemName: 'Marvel EasyFlo  (Grey colour)',
    itemCode: 'MAR001',
    companyName: "Marvel",
    category: "upvc",
    imageUrl: "assets/upvc/aquaflow.jpg",
    unit: "pice",
    subType: 'pipe',
    isCompanyItems: true,
    variants: [
      Variant(size: 'Plain Socket 3 mtrs  (4 Kg/cm2)', rate: 0.0),
      Variant(size: 'Plain Socket 6 mtrs  (4 Kg/cm2)', rate: 0.0),
      Variant(size: 'Plain Socket 3 mtrs  (6 Kg/cm2)', rate: 0.0),
      Variant(size: 'Plain Socket 6 mtrs  (6 Kg/cm2)', rate: 0.0),
      Variant(size: 'Single Socket (R/R) 3 mtrs  (Type A)', rate: 0.0),
    ],
  ),

  PriceListItem(
    itemName: 'COUPLER',
    unit: "piece",
    itemCode: 'UPVC101',
    companyName: "Marvel",
    category: "upvc",
    imageUrl: "assets/upvc/1.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1-1/4"', rate: 0),
      Variant(size: '1-1/2"', rate: 0),
      Variant(size: '2"', rate: 0),
      Variant(size: '2-1/2"', rate: 0),
      Variant(size: '4"', rate: 0),
      Variant(size: '6"', rate: 0),
      Variant(size: '8"', rate: 0),
      Variant(size: '8" (4 Kg/cm2)', rate: 0),
      Variant(size: '10"', rate: 0),
    ],
  ),

  PriceListItem(
    itemName: 'BEND 87.5° / ELBOW 90°',
    unit: "piece",
    itemCode: 'UPVC102',
    companyName: "Marvel",
    category: "upvc",
    imageUrl: "assets/upvc/2.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1-1/4"', rate: 0),
      Variant(size: '1-1/2"', rate: 0),
      Variant(size: '2"', rate: 0),
      Variant(size: '2-1/2"', rate: 0),
      Variant(size: '4"', rate: 0),
      Variant(size: '6"', rate: 0),
      Variant(size: '8"', rate: 0),
      Variant(size: '8" (4 Kg/cm2)', rate: 0),
      Variant(size: '10"', rate: 0),
      Variant(size: '10" (6 Kg/cm2)', rate: 0),
    ],
  ),

  PriceListItem(
    itemName: 'BEND 45°',
    unit: "piece",
    itemCode: 'UPVC103',
    companyName: "Marvel",
    category: "upvc",
    imageUrl: "assets/upvc/3.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1-1/4"', rate: 0),
      Variant(size: '1-1/2"', rate: 0),
      Variant(size: '2" (6 Kg/cm2)', rate: 0),
      Variant(size: '2-1/2"', rate: 0),
      Variant(size: '4"', rate: 0),
      Variant(size: '6"', rate: 0),
      Variant(size: '8" (4 Kg/cm2)', rate: 0),
      Variant(size: '8" (6 Kg/cm2)', rate: 0),
      Variant(size: '10" (6 Kg/cm2)', rate: 0),
    ],
  ),

  PriceListItem(
    itemName: 'BEND 87.5° WITH DOOR',
    unit: "piece",
    itemCode: 'UPVC104',
    companyName: "Marvel",
    category: "upvc",
    imageUrl: "assets/upvc/4.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '2-1/2"', rate: 0),
      Variant(size: '4"', rate: 0),
      Variant(size: '6"', rate: 0),
    ],
  ),

  PriceListItem(
    itemName: 'REPAIR COUPLER',
    unit: "piece",
    itemCode: 'UPVC005',
    companyName: "Marvel",
    category: "upvc",
    imageUrl: "assets/upvc/35.jpeg",
    isCompanyItems: true,
    variants: [
      Variant(size: '4"', rate: 0),
    ],
  ),

  PriceListItem(
    itemName: 'REDUCER COUPLER',
    unit: "piece",
    itemCode: 'UPVC006',
    companyName: "Marvel",
    category: "upvc",
    imageUrl: "assets/upvc/20.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '2x1-1/2"', rate: 0),
      Variant(size: '2-1/2x1-1/2"', rate: 0),
      Variant(size: '2-1/2x2"', rate: 0),
      Variant(size: '4x2-1/2"', rate: 0),
      Variant(size: '6x4"', rate: 0),
      Variant(size: '6x4" (Middle)', rate: 0),
      Variant(size: '8x6"', rate: 0),
    ],
  ),

  PriceListItem(
    itemName: 'SINGLE TEE',
    unit: "piece",
    itemCode: 'UPVC105',
    companyName: "Marvel",
    category: "upvc",
    imageUrl: "assets/upvc/5.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1-1/4"', rate: 0),
      Variant(size: '1-1/2"', rate: 0),
      Variant(size: '2"', rate: 0),
      Variant(size: '2-1/2"', rate: 0),
      Variant(size: '4"', rate: 0),
      Variant(size: '6"', rate: 0),
      Variant(size: '8"', rate: 0),
      Variant(size: '8" (4 Kg/cm2)', rate: 0),
      Variant(size: '10"', rate: 0),
      Variant(size: '10" (6 Kg/cm2)', rate: 0),
    ],
  ),

  PriceListItem(
    itemName: 'SINGLE TEE WITH DOOR',
    unit: "piece",
    itemCode: 'UPVC106',
    companyName: "Marvel",
    category: "upvc",
    imageUrl: "assets/upvc/6.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '2-1/2"', rate: 0),
      Variant(size: '4"', rate: 0),
      Variant(size: '6"', rate: 0),
    ],
  ),

  PriceListItem(
    itemName: 'REDUCING TEE',
    unit: "piece",
    itemCode: 'UPVC009',
    companyName: "Marvel",
    category: "upvc",
    imageUrl: "assets/upvc/9.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '4x2-1/2"', rate: 0),
      Variant(size: '6x4"', rate: 0),
      Variant(size: '8x6"', rate: 0),
    ],
  ),

  PriceListItem(
    itemName: 'REDUCING TEE WITH DOOR',
    unit: "piece",
    itemCode: 'UPVC010',
    companyName: "Marvel",
    category: "upvc",
    imageUrl: "assets/upvc/9.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '4x2-1/2"', rate: 0),
      Variant(size: '6x4"', rate: 0),
    ],
  ),

  PriceListItem(
    itemName: 'CLEANING PIPE',
    unit: "piece",
    itemCode: 'UPVC011',
    companyName: "Marvel",
    category: "upvc",
    imageUrl: "assets/upvc/19.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '2-1/2"', rate: 0),
      Variant(size: '4"', rate: 0),
      Variant(size: '6"', rate: 0),
      Variant(size: '8"', rate: 0),
      Variant(size: '10"', rate: 0),
    ],
  ),

  PriceListItem(
    itemName: 'CROSS TEE',
    unit: "piece",
    itemCode: 'UPVC107',
    companyName: "Marvel",
    category: "upvc",
    imageUrl: "assets/upvc/10.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '2-1/2"', rate: 0),
      Variant(size: '4"', rate: 0),
      Variant(size: '6"', rate: 0),
    ],
  ),

  PriceListItem(
    itemName: 'CROSS TEE WITH DOOR',
    unit: "piece",
    itemCode: 'UPVC013',
    companyName: "Marvel",
    category: "upvc",
    imageUrl: "assets/upvc/11.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '2-1/2"', rate: 0),
      Variant(size: '4"', rate: 0),
    ],
  ),

  PriceListItem(
    itemName: 'SINGLE "Y"',
    unit: "piece",
    itemCode: 'UPVC014',
    companyName: "Marvel",
    category: "upvc",
    imageUrl: "assets/upvc/15.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1-1/2"', rate: 0),
      Variant(size: '2" (6 Kg/cm2)', rate: 0),
      Variant(size: '2-1/2"', rate: 0),
      Variant(size: '4"', rate: 0),
      Variant(size: '6"', rate: 0),
      Variant(size: '8" (6 Kg/cm2)', rate: 0),
    ],
  ),

  PriceListItem(
    itemName: 'SINGLE "Y" WITH DOOR',
    unit: "piece",
    itemCode: 'UPVC015',
    companyName: "Marvel",
    category: "upvc",
    imageUrl: "assets/upvc/16.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '2-1/2"', rate: 0),
      Variant(size: '4"', rate: 0),
      Variant(size: '6"', rate: 0),
    ],
  ),

  PriceListItem(
    itemName: 'REDUCER "Y"',
    unit: "piece",
    itemCode: 'UPVC016',
    companyName: "Marvel",
    category: "upvc",
    imageUrl: "assets/upvc/8.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '4x2-1/2"', rate: 0),
      Variant(size: '6x4"', rate: 0),
      Variant(size: '6x4" (6 Kg/cm2)', rate: 0),
      Variant(size: '8x6"', rate: 0),
    ],
  ),

  PriceListItem(
    itemName: 'REDUCER "Y" WITH DOOR',
    unit: "piece",
    itemCode: 'UPVC017',
    companyName: "Marvel",
    category: "upvc",
    imageUrl: "assets/upvc/reducerywithdoor.jpeg",
    isCompanyItems: true,
    variants: [
      Variant(size: '4x2-1/2"', rate: 0),
      Variant(size: '6x4"', rate: 0),
    ],
  ),

  PriceListItem(
    itemName: 'DOUBLE "Y"',
    unit: "piece",
    itemCode: 'UPVC018',
    companyName: "Marvel",
    category: "upvc",
    imageUrl: "assets/upvc/17.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '2-1/2"', rate: 0),
      Variant(size: '4"', rate: 0),
    ],
  ),

  PriceListItem(
    itemName: 'DOUBLE "Y" WITH DOOR',
    unit: "piece",
    itemCode: 'UPVC019',
    companyName: "Marvel",
    category: "upvc",
    imageUrl: "assets/upvc/18.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '2-1/2"', rate: 0),
      Variant(size: '4"', rate: 0),
    ],
  ),

  PriceListItem(
    itemName: 'RUBBER LUBRICANT',
    unit: "piece",
    itemCode: 'UPVC020',
    companyName: "Marvel",
    category: "upvc",
    imageUrl: "assets/upvc/Rubber_lubricant.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '100 gms', rate: 0),
      Variant(size: '250 gms', rate: 0),
    ],
  ),

  PriceListItem(
    itemName: 'P-TRAP',
    unit: "piece",
    itemCode: 'UPVC021',
    companyName: "Marvel",
    category: "upvc",
    imageUrl: "assets/upvc/23.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '2-1/2x2-1/2"', rate: 0),
      Variant(size: '4x4"', rate: 0),
    ],
  ),

  PriceListItem(
    itemName: 'BELL MOUTH TRAP',
    unit: "piece",
    itemCode: 'UPVC022',
    companyName: "Marvel",
    category: "upvc",
    imageUrl: "assets/upvc/39.jpg",
    isCompanyItems: true,
    variants: [
      Variant(size: '4x2-1/2"', rate: 0),
    ],
  ),

  PriceListItem(
    itemName: 'MULTI FLOOR TRAP',
    unit: "piece",
    itemCode: 'UPVC023',
    companyName: "Marvel",
    category: "upvc",
    imageUrl: "assets/upvc/26.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '4x2-1/2" (without Jali)', rate: 0),
      Variant(size: '4x2-1/2" (with  SS Jali)', rate: 0),
      Variant(size: '4x2-1/2" (with  SS Jali)', rate: 0),
    ],
  ),

  PriceListItem(
    itemName: 'NEO MULTI FLOOR TRAP',
    unit: "piece",
    itemCode: 'UPVC024',
    companyName: "Marvel",
    category: "upvc",
    imageUrl: "assets/upvc/neo_multifloor.jpg",
    isCompanyItems: true,
    variants: [
      Variant(size: '4x4" (without Jali)', rate: 0),
      Variant(size: '4x2-1/2" (without Jali)', rate: 0),
    ],
  ),

  PriceListItem(
    itemName: 'NAHANI TRAP',
    unit: "piece",
    itemCode: 'UPVC025',
    companyName: "Marvel",
    category: "upvc",
    imageUrl: "assets/upvc/28.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '3x1-1/2" (with Jali)', rate: 0),
      Variant(size: '4x2-1/2" (without Jali)', rate: 0),
    ],
  ),

  PriceListItem(
    itemName: 'JALI',
    unit: "piece",
    itemCode: 'UPVC026',
    companyName: "Marvel",
    category: "upvc",
    imageUrl: "assets/upvc/30.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '5" (Square SS Jali)', rate: 0),
      Variant(size: '6" (Square SS Jali)', rate: 0),
      Variant(size: '4" (Round Plastic Jali)', rate: 0),
    ],
  ),

  PriceListItem(
    itemName: 'SOCKET PLUG',
    unit: "piece",
    itemCode: 'UPVC027',
    companyName: "Marvel",
    category: "upvc",
    imageUrl: "assets/upvc/14.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1-1/2"', rate: 0),
      Variant(size: '2-1/2"', rate: 0),
      Variant(size: '4"', rate: 0),
    ],
  ),

  PriceListItem(
    itemName: 'END CAP',
    unit: "piece",
    itemCode: 'UPVC027',
    companyName: "Marvel",
    category: "upvc",
    imageUrl: "assets/upvc/31.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1-1/4"', rate: 0),
      Variant(size: '1-1/2"', rate: 0),
      Variant(size: '2"', rate: 0),
      Variant(size: '2-1/2"', rate: 0),
      Variant(size: '4"', rate: 0),
      Variant(size: '6"', rate: 0),
      Variant(size: '8"', rate: 0),
      Variant(size: '10"', rate: 0),
    ],
  ),

  PriceListItem(
    itemName: 'VENT COWL',
    unit: "piece",
    itemCode: 'UPVC027',
    companyName: "Marvel",
    category: "upvc",
    imageUrl: "assets/upvc/13.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1-1/2"', rate: 0),
      Variant(size: '2-1/2"', rate: 0),
      Variant(size: '4"', rate: 0),
      Variant(size: '6"', rate: 0),
    ],
  ),

  PriceListItem(
    itemName: 'W.C. CONNECTOR WITH LIP RING',
    unit: "piece",
    itemCode: 'UPVC027',
    companyName: "Marvel",
    category: "upvc",
    imageUrl: "assets/upvc/29.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '4" (Bend Type)', rate: 0),
      Variant(size: '4" (Straight Type)', rate: 0),
    ],
  ),

  PriceListItem(
    itemName: 'ADHESIVE SOLUTION (INDIAN)',
    unit: "piece",
    itemCode: 'UPVC027',
    companyName: "Marvel",
    category: "upvc",
    imageUrl: "assets/upvc/adheshivesolution.jpg",
    isCompanyItems: true,
    variants: [
      Variant(size: '50 ml', rate: 0),
      Variant(size: '118 ml', rate: 0),
      Variant(size: '237', rate: 0),
      Variant(size: '473 ml', rate: 0),
      Variant(size: '946 ml', rate: 0),
      Variant(size: '5 ltr', rate: 0),
    ],
  ),

  PriceListItem(
    itemName: 'MTA',
    unit: "piece",
    itemCode: 'UPVC029',
    companyName: "Marvel",
    category: "upvc",
    imageUrl: "assets/upvc/mta.jpg",
    isCompanyItems: true,
    variants: [
      Variant(size: '1-1/2"', rate: 0),
      Variant(size: '2"', rate: 0),
      Variant(size: '2-1/2"', rate: 0),
      Variant(size: '4"', rate: 0),
    ],
  ),

  PriceListItem(
    itemName: 'FTA',
    unit: "piece",
    itemCode: 'UPVC030',
    companyName: "Marvel",
    category: "upvc",
    imageUrl: "assets/upvc/fta.jpg",
    isCompanyItems: true,
    variants: [
      Variant(size: '1-1/2"', rate: 0),
      Variant(size: '2"', rate: 0),
      Variant(size: '2-1/2"', rate: 0),
      Variant(size: '4"', rate: 0),
    ],
  ),

  PriceListItem(
    itemName: 'GULLY TRAP',
    unit: "piece",
    itemCode: 'UPVC031',
    companyName: "Marvel",
    category: "upvc",
    imageUrl: "assets/upvc/gully_trap.jpeg",
    isCompanyItems: true,
    variants: [
      Variant(size: '6x4"', rate: 0),
    ],
  ),

  PriceListItem(
    itemName: 'HEIGHT RISER / BOSS CONNECTOR',
    unit: "piece",
    itemCode: 'UPVC032',
    companyName: "Marvel",
    category: "upvc",
    imageUrl: "assets/upvc/height.jpg",
    isCompanyItems: true,
    variants: [
      Variant(size: '4x1-1/2"', rate: 0),
    ],
  ),

  PriceListItem(
    itemName: 'PIPE CLIP',
    unit: "piece",
    itemCode: 'UPVC033',
    companyName: "Marvel",
    category: "upvc",
    imageUrl: "assets/upvc/12.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1-1/2"', rate: 0),
      Variant(size: '2-1/2"', rate: 0),
      Variant(size: '4"', rate: 0),
      Variant(size: '6"', rate: 0),
    ],
  ),

  PriceListItem(
    itemName: 'METAL STRAP POWDER COATED GREY',
    unit: "piece",
    itemCode: 'UPVC034',
    companyName: "Marvel",
    category: "upvc",
    imageUrl: "assets/upvc/34.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1-1/2"', rate: 0),
      Variant(size: '2-1/2"', rate: 0),
      Variant(size: '4"', rate: 0),
      Variant(size: '6"', rate: 0),
    ],
  ),

  PriceListItem(
    itemName: 'SPLIT/HANGING CLAMP WITH EPDM WASHER',
    unit: "piece",
    itemCode: 'UPVC035',
    companyName: "Marvel",
    category: "upvc",
    imageUrl: "assets/upvc/split.jpg",
    isCompanyItems: true,
    variants: [
      Variant(size: '2-1/2"', rate: 0),
      Variant(size: '4"', rate: 0),
      Variant(size: '6"', rate: 0),
      Variant(size: '8"', rate: 0),
    ],
  ),

  PriceListItem(
    itemName: 'METAL GRIP',
    unit: "piece",
    itemCode: 'UPVC036',
    companyName: "Marvel",
    category: "upvc",
    imageUrl: "assets/upvc/metal_grip.jpg",
    isCompanyItems: true,
    variants: [
      Variant(size: '10mm', rate: 0),
    ],
  ),

  PriceListItem(
    itemName: 'THREADED ROD (2mtr Long)',
    unit: "piece",
    itemCode: 'UPVC037',
    companyName: "Marvel",
    category: "upvc",
    imageUrl: "assets/upvc/threadedrod.jpeg",
    isCompanyItems: true,
    variants: [
      Variant(size: '10mm', rate: 0),
    ],
  ),

  PriceListItem(
    itemName: 'ADHESIVE SOLUTION (E-Z Weld)',
    unit: "piece",
    itemCode: 'UPVC038',
    companyName: "Marvel",
    category: "upvc",
    imageUrl: "assets/upvc/36.jpeg",
    isCompanyItems: true,
    variants: [
      Variant(size: '118 ml 204 (Indian)', rate: 0),
      Variant(size: '237 ml 204 (Indian)', rate: 0),
      Variant(size: '473 ml 204 (Indian)', rate: 0),
    ],
  ),

  PriceListItem(
    itemName: 'PRIMER (E-Z Weld)',
    unit: "piece",
    itemCode: 'UPVC039',
    companyName: "Marvel",
    category: "upvc",
    imageUrl: "assets/upvc/37.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '237 ml 213 (USA)', rate: 0),
      Variant(size: '473 ml 213 (USA)', rate: 0),
    ],
  ),
];
