import 'package:hardwares/app/app_data/item_data_model.dart';

final List<PriceListItem> nepatopPriceList = [
  // ===================== PPR CATEGORY - NEPATOP (41 items) =====================
// PPR Pipes (3 items)
  PriceListItem(
    itemName: 'PPR Pipe SDR 11/Mtr ',
    itemCode: 'PPR1100',
    unit: "meter",
    companyName: "Nepatop",
    category: "ppr",
    imageUrl: "assets/ppr/ppr_pipe.jpeg",
    isCompanyItems: true,
    variants: [
      Variant(size: "20 mm", rate: 117.0),
      Variant(size: "25 mm", rate: 194.0),
      Variant(size: "32 mm", rate: 310.0),
      Variant(size: "40 mm", rate: 490.0),
      Variant(size: "50 mm", rate: 764.0),
      Variant(size: "63 mm", rate: 1176.0),
      Variant(size: "75 mm", rate: 1587.0),
      Variant(size: "90 mm", rate: 2279.0),
      Variant(size: "110 mm", rate: 3521.0),
    ],
  ),
  PriceListItem(
    itemName: 'PPR Pipe SDR 7.4/Mtr',
    itemCode: 'PPR1101',
    unit: "meter",
    companyName: "Nepatop",
    category: "ppr",
    imageUrl: "assets/ppr/ppr_pipe.jpeg",
    isCompanyItems: true,
    variants: [
      Variant(size: "20 mm", rate: 131.0),
      Variant(size: "25 mm", rate: 210.0),
      Variant(size: "32 mm", rate: 339.0),
      Variant(size: "40 mm", rate: 533.0),
      Variant(size: "50 mm", rate: 828.0),
      Variant(size: "63 mm", rate: 1280.0),
      Variant(size: "75 mm", rate: 1726.0),
      Variant(size: "90 mm", rate: 2478.0),
      Variant(size: "110 mm", rate: 3832.0),
    ],
  ),
  PriceListItem(
    itemName: 'PPR Pipe SDR 6/Mtr',
    itemCode: 'PPR1102',
    unit: "meter",
    companyName: "Nepatop",
    category: "ppr",
    imageUrl: "assets/ppr/ppr_pipe.jpeg",
    isCompanyItems: true,
    variants: [
      Variant(size: "20 mm", rate: 157.0),
      Variant(size: "25 mm", rate: 248.0),
      Variant(size: "32 mm", rate: 400.0),
      Variant(size: "40 mm", rate: 615.0),
      Variant(size: "50 mm", rate: 952.0),
      Variant(size: "63 mm", rate: 1480.0),
      Variant(size: "75 mm", rate: 2025.0),
      Variant(size: "90 mm", rate: 2919.0),
      Variant(size: "110 mm", rate: 4348.0),
    ],
  ),

// PPR Fittings
  PriceListItem(
    itemName: 'Socket',
    itemCode: 'PPR1103',
    companyName: "Nepatop",
    category: "ppr",
    imageUrl: "assets/ppr/ppr_socket.jpg",
    isCompanyItems: true,
    variants: [
      Variant(size: "20 mm", rate: 17.0),
      Variant(size: "25 mm", rate: 24.0),
      Variant(size: "32 mm", rate: 43.0),
      Variant(size: "40 mm", rate: 82.0),
      Variant(size: "50 mm", rate: 138.0),
      Variant(size: "63 mm", rate: 234.0),
      Variant(size: "75 mm", rate: 413.0),
      Variant(size: "90 mm", rate: 668.0),
      Variant(size: "110 mm", rate: 1220.0),
    ],
  ),
  PriceListItem(
    itemName: 'Elbow 90°',
    itemCode: 'PPR1104',
    companyName: "Nepatop",
    category: "ppr",
    imageUrl: "assets/ppr/ppr-90-degree-elbow.jpg",
    isCompanyItems: true,
    variants: [
      Variant(size: "20 mm", rate: 23.0),
      Variant(size: "25 mm", rate: 43.0),
      Variant(size: "32 mm", rate: 70.0),
      Variant(size: "40 mm", rate: 148.0),
      Variant(size: "50 mm", rate: 249.0),
      Variant(size: "63 mm", rate: 439.0),
      Variant(size: "75 mm", rate: 843.0),
      Variant(size: "90 mm", rate: 1376.0),
      Variant(size: "110 mm", rate: 2558.0),
    ],
  ),
  PriceListItem(
    itemName: 'Tee',
    itemCode: 'PPR1105',
    companyName: "Nepatop",
    category: "ppr",
    imageUrl: "assets/ppr/ppr_tee.jpg",
    isCompanyItems: true,
    variants: [
      Variant(size: "20 mm", rate: 30.0),
      Variant(size: "25 mm", rate: 50.0),
      Variant(size: "32 mm", rate: 88.0),
      Variant(size: "40 mm", rate: 173.0),
      Variant(size: "50 mm", rate: 287.0),
      Variant(size: "63 mm", rate: 522.0),
      Variant(size: "75 mm", rate: 987.0),
      Variant(size: "90 mm", rate: 1655.0),
      Variant(size: "110 mm", rate: 2874.0),
    ],
  ),
  PriceListItem(
    itemName: '45° Elbow',
    itemCode: 'PPR1106',
    companyName: "Nepatop",
    category: "ppr",
    imageUrl: "assets/ppr/ppr_45_elbo.jpg",
    isCompanyItems: true,
    variants: [
      Variant(size: "20 mm", rate: 29.0),
      Variant(size: "25 mm", rate: 48.0),
      Variant(size: "32 mm", rate: 73.0),
      Variant(size: "40 mm", rate: 141.0),
      Variant(size: "50 mm", rate: 238.0),
      Variant(size: "63 mm", rate: 370.0),
      Variant(size: "75 mm", rate: 875.0),
      Variant(size: "90 mm", rate: 1418.0),
      Variant(size: "110 mm", rate: 2613.0),
    ],
  ),
  PriceListItem(
    itemName: 'Female Tee',
    itemCode: 'PPR1107',
    companyName: "Nepatop",
    category: "ppr",
    imageUrl: "assets/ppr/ppr_female-tee.jpeg",
    isCompanyItems: true,
    variants: [
      Variant(size: "20 x 1/2\"", rate: 217.0),
      Variant(size: "20 x 3/4\"", rate: 219.0),
      Variant(size: "25 x 1/2\"", rate: 249.0),
      Variant(size: "25 x 3/4\"", rate: 326.0),
      Variant(size: "32 x 1/2\"", rate: 336.0),
      Variant(size: "32 x 3/4\"", rate: 370.0),
      Variant(size: "32 x 1\"", rate: 650.0),
      Variant(size: "40 x 1/2\"", rate: 1178.0),
      Variant(size: "40 x 5/4\"", rate: 1159.0),
      Variant(size: "50 x 6/4\"", rate: 1756.0),
      Variant(size: "63 x 1\"", rate: 2206.0),
      Variant(size: "63 x 2\"", rate: 2330.0),
    ],
  ),
  PriceListItem(
    itemName: 'Male Tee',
    itemCode: 'PPR1108',
    companyName: "Nepatop",
    category: "ppr",
    imageUrl: "assets/ppr/ppr_male-tee.jpeg",
    isCompanyItems: true,
    variants: [
      Variant(size: "20 x 1/2\"", rate: 297.0),
      Variant(size: "20 x 3/4\"", rate: 284.0),
      Variant(size: "25 x 1/2\"", rate: 290.0),
      Variant(size: "25 x 3/4\"", rate: 359.0),
      Variant(size: "32 x 1/2\"", rate: 406.0),
      Variant(size: "32 x 3/4\"", rate: 415.0),
      Variant(size: "32 x 1\"", rate: 815.0),
      Variant(size: "40 x 1/2\"", rate: 1321.0),
      Variant(size: "40 x 5/4\"", rate: 1285.0),
      Variant(size: "50 x 6/4\"", rate: 2036.0),
      Variant(size: "63 x 1\"", rate: 2423.0),
      Variant(size: "63 x 2\"", rate: 2630.0),
    ],
  ),
  PriceListItem(
    itemName: 'Male Seated Elbow',
    itemCode: 'PPR1109',
    companyName: "Nepatop",
    category: "ppr",
    imageUrl: "assets/ppr/ppr_male_seated_elbo.jpeg",
    isCompanyItems: true,
    variants: [
      Variant(size: "20 x 1/2\"", rate: 273.0),
      Variant(size: "25 x 1/2\"", rate: 313.0),
      Variant(size: "25 x 3/4\"", rate: 348.0),
    ],
  ),
  PriceListItem(
    itemName: 'Plug',
    itemCode: 'PPR1110',
    companyName: "Nepatop",
    category: "ppr",
    imageUrl: "assets/ppr/ppr_plug.jpeg",
    isCompanyItems: true,
    variants: [
      Variant(size: "20 mm", rate: 13.0),
      Variant(size: "25 mm", rate: 21.0),
      Variant(size: "32 mm", rate: 26.0),
    ],
  ),
  PriceListItem(
    itemName: 'Cross Tee',
    itemCode: 'PPR1111',
    companyName: "Nepatop",
    category: "ppr",
    imageUrl: "assets/ppr/ppr_corss_tee.jpeg",
    isCompanyItems: true,
    variants: [
      Variant(size: "20 mm", rate: 52.0),
      Variant(size: "25 mm", rate: 73.0),
      Variant(size: "32 mm", rate: 129.0),
      Variant(size: "40 mm", rate: 250.0),
      Variant(size: "50 mm", rate: 681.0),
      Variant(size: "63 mm", rate: 701.0),
    ],
  ),
  PriceListItem(
    itemName: 'Union',
    itemCode: 'PPR1112',
    companyName: "Nepatop",
    category: "ppr",
    imageUrl: "assets/ppr/ppr-union.jpg",
    isCompanyItems: true,
    variants: [
      Variant(size: "20 mm", rate: 98.0),
      Variant(size: "25 mm", rate: 167.0),
      Variant(size: "32 mm", rate: 263.0),
      Variant(size: "40 mm", rate: 451.0),
      Variant(size: "50 mm", rate: 707.0),
      Variant(size: "63 mm", rate: 844.0),
    ],
  ),
  PriceListItem(
    itemName: 'Reducer Tee',
    itemCode: 'PPR1113',
    companyName: "Nepatop",
    category: "ppr",
    imageUrl: "assets/ppr/ppr_reducer_tee.jpg",
    isCompanyItems: true,
    variants: [
      Variant(size: "25x20x20", rate: 40.0),
      Variant(size: "25x20x25", rate: 51.0),
      Variant(size: "32x20x20", rate: 91.0),
      Variant(size: "32x20x32", rate: 83.0),
      Variant(size: "32x25x20", rate: 98.0),
      Variant(size: "32x25x32", rate: 87.0),
      Variant(size: "40x20x40", rate: 126.0),
      Variant(size: "40x25x40", rate: 129.0),
      Variant(size: "40x32x40", rate: 145.0),
      Variant(size: "50x20x50", rate: 281.0),
      Variant(size: "50x25x50", rate: 266.0),
      Variant(size: "50x32x50", rate: 292.0),
      Variant(size: "50x40x50", rate: 310.0),
      Variant(size: "63x20x63", rate: 365.0),
      Variant(size: "63x25x63", rate: 377.0),
      Variant(size: "63x32x63", rate: 388.0),
      Variant(size: "63x40x63", rate: 393.0),
      Variant(size: "63x50x63", rate: 399.0),
    ],
  ),
  PriceListItem(
    itemName: 'Reducer Elbow',
    itemCode: 'PPR1114',
    companyName: "Nepatop",
    category: "ppr",
    imageUrl: "assets/ppr/ppr_reducer_elbow.png",
    isCompanyItems: true,
    variants: [
      Variant(size: "20 x 25", rate: 42.0),
      Variant(size: "32 x 20", rate: 61.0),
      Variant(size: "32 x 25", rate: 77.0),
      Variant(size: "40 x 20", rate: 140.0),
      Variant(size: "40 x 25", rate: 152.0),
      Variant(size: "40 x 32", rate: 188.0),
    ],
  ),
  PriceListItem(
    itemName: 'Caps',
    itemCode: 'PPR1115',
    companyName: "Nepatop",
    category: "ppr",
    imageUrl: "assets/ppr/ppr_caps.jpeg",
    isCompanyItems: true,
    variants: [
      Variant(size: "20 mm", rate: 31.0),
      Variant(size: "25 mm", rate: 46.0),
      Variant(size: "32 mm", rate: 70.0),
      Variant(size: "40 mm", rate: 111.0),
      Variant(size: "50 mm", rate: 187.0),
      Variant(size: "63 mm", rate: 338.0),
      Variant(size: "75 mm", rate: 515.0),
      Variant(size: "90 mm", rate: 576.0),
      Variant(size: "110 mm", rate: 1182.0),
    ],
  ),

  PriceListItem(
    itemName: 'Male Socket',
    itemCode: 'PPR1116',
    companyName: "Nepatop",
    category: "ppr",
    imageUrl: "assets/ppr/ppr-male-socket.jpeg",
    isCompanyItems: true,
    variants: [
      Variant(size: "20 x 1/2\"", rate: 251.0),
      Variant(size: "20 x 3/4\"", rate: 301.0),
      Variant(size: "25 x 1/2\"", rate: 266.0),
      Variant(size: "25 x 3/4\"", rate: 305.0),
      Variant(size: "32 x 1/2\"", rate: 339.0),
      Variant(size: "32 x 3/4\"", rate: 356.0),
      Variant(size: "32 x 1\"", rate: 677.0),
      Variant(size: "40 x 5/4\"", rate: 1120.0),
      Variant(size: "50 x 6/4\"", rate: 1807.0),
      Variant(size: "63 x 2\"", rate: 2406.0),
    ],
  ),
  PriceListItem(
    itemName: 'Female Socket',
    itemCode: 'PPR1117',
    companyName: "Nepatop",
    category: "ppr",
    imageUrl: "assets/ppr/ppr-female-socket.jpeg",
    isCompanyItems: true,
    variants: [
      Variant(size: "20 x 1/2\"", rate: 190.0),
      Variant(size: "20 x 3/4\"", rate: 216.0),
      Variant(size: "25 x 1/2\"", rate: 234.0),
      Variant(size: "25 x 3/4\"", rate: 237.0),
      Variant(size: "32 x 1/2\"", rate: 227.0),
      Variant(size: "32 x 3/4\"", rate: 244.0),
      Variant(size: "32 x 1\"", rate: 528.0),
      Variant(size: "40 x 5/4\"", rate: 983.0),
      Variant(size: "50 x 6/4\"", rate: 1364.0),
      Variant(size: "63 x 2\"", rate: 1846.0),
    ],
  ),
  PriceListItem(
    itemName: 'Plastic Flange',
    itemCode: 'PPR1118',
    companyName: "Nepatop",
    category: "ppr",
    imageUrl: "assets/ppr/ppr_plastic-flange.jpeg",
    isCompanyItems: true,
    variants: [
      Variant(size: "40 mm", rate: 263.0),
      Variant(size: "50 mm", rate: 439.0),
      Variant(size: "63 mm", rate: 564.0),
      Variant(size: "75 mm", rate: 1165.0),
      Variant(size: "90 mm", rate: 1521.0),
      Variant(size: "110 mm", rate: 2056.0),
    ],
  ),
  PriceListItem(
    itemName: 'Female Elbow',
    itemCode: 'PPR1119',
    companyName: "Nepatop",
    category: "ppr",
    imageUrl: "assets/ppr/ppr-female-elbow.jpg",
    isCompanyItems: true,
    variants: [
      Variant(size: "20 x 1/2\"", rate: 215.0),
      Variant(size: "25 x 1/2\"", rate: 303.0),
      Variant(size: "25 x 3/4\"", rate: 277.0),
      Variant(size: "32 x 1/2\"", rate: 373.0),
      Variant(size: "32 x 3/4\"", rate: 425.0),
      Variant(size: "32 x 1\"", rate: 574.0),
      Variant(size: "40 x 5/4\"", rate: 1161.0),
      Variant(size: "50 x 6/4\"", rate: 1337.0),
      Variant(size: "63 x 2\"", rate: 1538.0),
    ],
  ),
  PriceListItem(
    itemName: 'Male Elbow',
    itemCode: 'PPR1120',
    companyName: "Nepatop",
    category: "ppr",
    imageUrl: "assets/ppr/ppr-male-elbow.jpeg",
    isCompanyItems: true,
    variants: [
      Variant(size: "20 x 1/2\"", rate: 285.0),
      Variant(size: "25 x 1/2\"", rate: 294.0),
      Variant(size: "25 x 3/4\"", rate: 354.0),
      Variant(size: "32 x 1/2\"", rate: 533.0),
      Variant(size: "32 x 3/4\"", rate: 380.0),
      Variant(size: "32 x 1\"", rate: 808.0),
      Variant(size: "40 x 5/4\"", rate: 1185.0),
    ],
  ),
  PriceListItem(
    itemName: 'Reducer Socket',
    itemCode: 'PPR1121',
    companyName: "Nepatop",
    category: "ppr",
    imageUrl: "assets/ppr/ppr_reducer-socket.jpeg",
    isCompanyItems: true,
    variants: [
      Variant(size: "20 x 25", rate: 29.0),
      Variant(size: "32 x 20", rate: 37.0),
      Variant(size: "32 x 25", rate: 42.0),
      Variant(size: "40 x 20", rate: 59.0),
      Variant(size: "40 x 25", rate: 71.0),
      Variant(size: "40 x 32", rate: 82.0),
      Variant(size: "50 x 20", rate: 108.0),
      Variant(size: "50 x 25", rate: 119.0),
      Variant(size: "50 x 32", rate: 129.0),
      Variant(size: "50 x 40", rate: 155.0),
      Variant(size: "63 x 20", rate: 197.0),
      Variant(size: "63 x 25", rate: 218.0),
      Variant(size: "63 x 32", rate: 222.0),
      Variant(size: "63 x 40", rate: 229.0),
      Variant(size: "63 x 50", rate: 247.0),
    ],
  ),
  PriceListItem(
    itemName: 'Double Female Elbow',
    itemCode: 'PPR1122',
    companyName: "Nepatop",
    category: "ppr",
    imageUrl: "assets/ppr/ppr_double-female-elbow.jpeg",
    isCompanyItems: true,
    variants: [
      Variant(size: "20 x 1/2\"", rate: 512.0),
      Variant(size: "25 x 1/2\"", rate: 588.0),
    ],
  ),
  PriceListItem(
    itemName: 'Plug Nipple',
    itemCode: 'PPR1123',
    companyName: "Nepatop",
    category: "ppr",
    imageUrl: "assets/ppr/ppr_plug-nipple.jpeg",
    isCompanyItems: true,
    variants: [
      Variant(size: "20 mm", rate: 23.0),
    ],
  ),
  PriceListItem(
    itemName: 'PPR Filter (Stainer)',
    itemCode: 'PPR1124',
    companyName: "Nepatop",
    category: "ppr",
    imageUrl: "assets/ppr/ppr-filter-stainer.jpeg",
    isCompanyItems: true,
    variants: [
      Variant(size: "20 mm", rate: 352.0),
      Variant(size: "25 mm", rate: 494.0),
      Variant(size: "32 mm", rate: 782.0),
    ],
  ),
  PriceListItem(
    itemName: 'Female Seated Elbow',
    itemCode: 'PPR1125',
    companyName: "Nepatop",
    category: "ppr",
    imageUrl: "assets/ppr/ppr_female-seated-elbow-heavy.jpeg",
    isCompanyItems: true,
    variants: [
      Variant(size: "20 x 1/2\"", rate: 295.0),
      Variant(size: "25 x 1/2\"", rate: 370.0),
      Variant(size: "25 x 3/4\"", rate: 387.0),
    ],
  ),
  PriceListItem(
    itemName: 'Pipe Tank Nipple',
    itemCode: 'PPR1127',
    companyName: "Nepatop",
    category: "ppr",
    imageUrl: "assets/ppr/pipe_tank_nipple.png",
    isCompanyItems: true,
    variants: [
      Variant(size: "32 mm", rate: 297.0),
    ],
  ),
  PriceListItem(
    itemName: 'Tank Nipple',
    itemCode: 'PPR1128',
    companyName: "Nepatop",
    category: "ppr",
    imageUrl: "assets/ppr/ppr_tank_nipple.jpg",
    isCompanyItems: true,
    variants: [
      Variant(size: "32 mm", rate: 529.0),
      Variant(size: "40 mm", rate: 655.0),
    ],
  ),
  PriceListItem(
    itemName: 'Stop Valve',
    itemCode: 'PPR1129',
    companyName: "Nepatop",
    category: "ppr",
    imageUrl: "assets/ppr/stop_valve.jpg",
    isCompanyItems: true,
    variants: [
      Variant(size: "20 mm", rate: 511.0),
      Variant(size: "25 mm", rate: 675.0),
      Variant(size: "32 mm", rate: 820.0),
      Variant(size: "40 mm", rate: 1086.0),
      Variant(size: "50 mm", rate: 1799.0),
      Variant(size: "63 mm", rate: 2621.0),
      Variant(size: "75 mm", rate: 4984.0),
      Variant(size: "90 mm", rate: 5456.0),
      Variant(size: "110 mm", rate: 7455.0),
    ],
  ),
  PriceListItem(
    itemName: 'Plastic Ball Valve',
    itemCode: 'PPR1130',
    companyName: "Nepatop",
    category: "ppr",
    imageUrl: "assets/ppr/plastic_ball_valve.jpg",
    isCompanyItems: true,
    variants: [
      Variant(size: "20 mm", rate: 170.0),
      Variant(size: "25 mm", rate: 218.0),
      Variant(size: "32 mm", rate: 372.0),
      Variant(size: "40 mm", rate: 1033.0),
      Variant(size: "50 mm", rate: 1433.0),
      Variant(size: "63 mm", rate: 2328.0),
      Variant(size: "75 mm", rate: 3267.0),
      Variant(size: "90 mm", rate: 6475.0),
      Variant(size: "110 mm", rate: 8855.0),
    ],
  ),
  PriceListItem(
    itemName: 'Ball Valve Metal Body',
    itemCode: 'PPR1131',
    companyName: "Nepatop",
    category: "ppr",
    imageUrl: "assets/ppr/ppr-ball-valve-metal.jpeg",
    isCompanyItems: true,
    variants: [
      Variant(size: "20 mm", rate: 1184.0),
      Variant(size: "25 mm", rate: 1608.0),
      Variant(size: "32 mm", rate: 2333.0),
      Variant(size: "40 mm", rate: 3104.0),
      Variant(size: "50 mm", rate: 3883.0),
      Variant(size: "63 mm", rate: 4970.0),
      Variant(size: "75 mm", rate: 13449.0),
      Variant(size: "90 mm", rate: 24770.0),
      Variant(size: "110 mm", rate: 26124.0),
    ],
  ),
  PriceListItem(
    itemName: 'Ball Valve Female',
    itemCode: 'PPR1132',
    companyName: "Nepatop",
    category: "ppr",
    imageUrl: "assets/ppr/ball-valve-female.jpeg",
    isCompanyItems: true,
    variants: [
      Variant(size: "20 mm", rate: 1184.0),
      Variant(size: "25 mm", rate: 1608.0),
      Variant(size: "32 mm", rate: 2333.0),
      Variant(size: "40 mm", rate: 3104.0),
      Variant(size: "50 mm", rate: 3883.0),
      Variant(size: "63 mm", rate: 4970.0),
      Variant(size: "75 mm", rate: 13449.0),
      Variant(size: "90 mm", rate: 21770.0),
      Variant(size: "110 mm", rate: 26124.0),
    ],
  ),

  PriceListItem(
    itemName: 'Brass Ball Valve',
    itemCode: 'PPR1133',
    companyName: "Nepatop",
    category: "ppr",
    imageUrl: "assets/ppr/brass_ball_valve.jpg",
    isCompanyItems: true,
    variants: [
      Variant(size: "20 mm", rate: 516.0),
      Variant(size: "25 mm", rate: 720.0),
      Variant(size: "32 mm", rate: 1210.0),
      Variant(size: "40 mm", rate: 2004.0),
    ],
  ),
  PriceListItem(
    itemName: 'Cross Over',
    itemCode: 'PPR1134',
    companyName: "Nepatop",
    category: "ppr",
    imageUrl: "assets/ppr/ppr_cross_over.jpeg",
    isCompanyItems: true,
    variants: [
      Variant(size: "20 mm", rate: 142.0),
      Variant(size: "25 mm", rate: 203.0),
      Variant(size: "32 mm", rate: 294.0),
    ],
  ),
  PriceListItem(
    itemName: 'Heat Gate Valve',
    itemCode: 'PPR1137',
    companyName: "Nepatop",
    category: "ppr",
    imageUrl: "assets/ppr/ppr_Heat_Gate_Valve.jpg",
    isCompanyItems: true,
    variants: [
      Variant(size: "20 mm", rate: 549.0),
      Variant(size: "25 mm", rate: 648.0),
      Variant(size: "32 mm", rate: 802.0),
      Variant(size: "40 mm", rate: 1108.0),
      Variant(size: "50 mm", rate: 1559.0),
      Variant(size: "63 mm", rate: 1699.0),
      Variant(size: "75 mm", rate: 1869.0),
      Variant(size: "90 mm", rate: 1961.0),
      Variant(size: "110 mm", rate: 2063.0),
    ],
  ),
  PriceListItem(
    itemName: 'U Clamp',
    itemCode: 'PPR1138',
    companyName: "Nepatop",
    category: "ppr",
    imageUrl: "assets/ppr/ppr_u-clam.jpeg",
    isCompanyItems: true,
    variants: [
      Variant(size: "20 mm", rate: 13.0),
      Variant(size: "25 mm", rate: 16.0),
      Variant(size: "32 mm", rate: 30.0),
      Variant(size: "40 mm", rate: 37.0),
      Variant(size: "50 mm", rate: 59.0),
      Variant(size: "63 mm", rate: 76.0),
    ],
  ),
  PriceListItem(
    itemName: 'U Clamp Long',
    itemCode: 'PPR1139',
    companyName: "Nepatop",
    category: "ppr",
    imageUrl: "assets/ppr/ppr_u-clamp-long.jpeg",
    isCompanyItems: true,
    variants: [
      Variant(size: "20 mm", rate: 30.0),
      Variant(size: "25 mm", rate: 34.0),
      Variant(size: "32 mm", rate: 46.0),
      Variant(size: "40 mm", rate: 52.0),
      Variant(size: "50 mm", rate: 70.0),
      Variant(size: "63 mm", rate: 78.0),
    ],
  ),

// -------------------upvc ------------------------------------

  PriceListItem(
    itemName: 'Nepatop Plus uPVC Pipes (NS 206/046)',
    itemCode: 'NEP001',
    companyName: "Nepatop",
    category: "upvc",
    imageUrl: "assets/upvc/pipes.jpeg",
    unit: "meter",
    isCompanyItems: true,
    variants: [
      // 2.5 Kg/cm2 variants
      Variant(
        size: '110mm (2.5 Kg/cm2)',
        rate: 433.0,
      ),
      Variant(
        size: '160mm (2.5 Kg/cm2)',
        rate: 836.0,
      ),
      Variant(
        size: '200mm  (2.5 Kg/cm2)',
        rate: 1385.0,
      ),

      // 4 Kg/cm2 variants
      Variant(
        size: '75mm (4 Kg/cm2)',
        rate: 310.0,
      ),
      Variant(
        size: '110mm (4 Kg/cm2)',
        rate: 595.0,
      ),
      Variant(
        size: '160mm (4 Kg/cm2)',
        rate: 1321.0,
      ),
      Variant(
        size: '200mm (4 Kg/cm2) ',
        rate: 2190.0,
      ),

      // 6 Kg/cm2 variants
      Variant(
        size: '50mm (6 Kg/cm2)',
        rate: 185.0,
      ),
      Variant(
        size: '75mm (6 Kg/cm2)',
        rate: 457.0,
      ),
      Variant(
        size: '110mm (6 Kg/cm2)',
        rate: 929.0,
      ),
      Variant(
        size: '160mm (6 Kg/cm2)',
        rate: 2057.0,
      ),
      Variant(
        size: '200mm (6 Kg/cm2)',
        rate: 3421.0,
      ),
    ],
  ),

  // Single item for Nepatop uPVC Pipes IS 13592
  PriceListItem(
    itemName: 'Nepatop uPVC Pipes (IS 13592)',
    itemCode: 'NEP002',
    companyName: "Nepatop",
    category: "upvc",
    imageUrl: "assets/upvc/pipes.jpeg",
    unit: "meter",
    isCompanyItems: true,
    variants: [
      Variant(size: '50mm ', rate: 157.0),
      Variant(size: '75mm ', rate: 250.0),
      Variant(size: '110mm ', rate: 491.0),
      Variant(size: '160mm ', rate: 1037.0),
      Variant(size: '200mm ', rate: 1601.0),
    ],
  ),

  // Duradrain
  PriceListItem(
    itemName: 'Duradrain',
    itemCode: 'NEP003',
    companyName: "Nepatop",
    category: "upvc",
    imageUrl: "assets/upvc/pipes.jpeg",
    unit: "meter",
    isCompanyItems: true,
    variants: [
      Variant(size: '110 mm SN 8 ', rate: 834.0),
      Variant(size: '75 mm SN 8 ', rate: 414.0),
    ],
  ),

  // Insulation Pipes
  PriceListItem(
    itemName: 'Insulation Pipe',
    itemCode: 'NEP004',
    companyName: "Nepatop",
    category: "upvc",
    imageUrl: "assets/upvc/pipes.jpeg",
    unit: "pic",
    isCompanyItems: true,
    variants: [
      Variant(size: '20mm', rate: 206.0),
      Variant(size: '25mm', rate: 242.0),
      Variant(size: '32mm', rate: 294.0),
    ],
  ),

  // Chemicals consolidated

  PriceListItem(
    itemName: 'PVC Solvent Cement',
    itemCode: 'NEP006',
    companyName: "Nepatop",
    category: "additional_items",
    imageUrl: "assets/upvc/solvent.jpg",
    unit: "pic",
    isCompanyItems: false,
    variants: [
      Variant(size: '100ml', rate: 162.0),
      Variant(size: '250ml', rate: 295.0),
      Variant(size: '1000ml', rate: 867.0),
      Variant(size: '200ml', rate: 236.0),
      Variant(size: '500ml', rate: 590.0),
    ],
  ),

  PriceListItem(
    itemName: 'Rubber Lubricants',
    itemCode: 'NEP007',
    companyName: "Nepatop",
    category: "additional_items",
    imageUrl: "assets/upvc/Rubber_lubricant.png",
    unit: "pic",
    isCompanyItems: false,
    variants: [
      Variant(size: '250 Grm', rate: 109.0),
    ],
  ),

  PriceListItem(
    itemName: 'Socket (coupler)',
    itemCode: 'UPVC101', // Changed from UPVC1001
    companyName: "Nepatop",
    category: "upvc",
    imageUrl: "assets/upvc/1.png",
    isCompanyItems: true,
    variants: [
      Variant(size: "50 mm", rate: 74.0),
      Variant(size: "75 mm", rate: 160.0),
      Variant(size: "110 mm", rate: 280.0),
      Variant(size: "160 mm", rate: 614.0),
    ],
  ),
  PriceListItem(
    itemName: 'Bend 87.5°',
    itemCode: 'UPVC102', // Changed from UPVC1002
    companyName: "Nepatop",
    category: "upvc",
    imageUrl: "assets/upvc/2.png",
    isCompanyItems: true,
    variants: [
      Variant(size: "50 mm", rate: 76.0),
      Variant(size: "75 mm", rate: 215.0),
      Variant(size: "110 mm", rate: 387.0),
      Variant(size: "160 mm", rate: 973.0),
    ],
  ),
  PriceListItem(
    itemName: 'Bend 45°',
    itemCode: 'UPVC103', // Changed from UPVC1003
    companyName: "Nepatop",
    category: "upvc",
    imageUrl: "assets/upvc/3.png",
    isCompanyItems: true,
    variants: [
      Variant(size: "50 mm", rate: 76.0),
      Variant(size: "75 mm", rate: 186.0),
      Variant(size: "110 mm", rate: 335.0),
      Variant(size: "160 mm", rate: 923.0),
    ],
  ),
  PriceListItem(
    itemName: 'Bend 87.5° With Door',
    itemCode: 'UPVC104', // Changed from UPVC1004
    companyName: "Nepatop",
    category: "upvc",
    imageUrl: "assets/upvc/4.png",
    isCompanyItems: true,
    variants: [
      Variant(size: "75 mm", rate: 291.0),
      Variant(size: "110 mm", rate: 475.0),
      Variant(size: "160 mm", rate: 1433.0),
    ],
  ),
  PriceListItem(
    itemName: 'Single Tee',
    itemCode: 'UPVC105', // Changed from UPVC1005
    companyName: "Nepatop",
    category: "upvc",
    imageUrl: "assets/upvc/5.png",
    isCompanyItems: true,
    variants: [
      Variant(size: "50 mm", rate: 153.0),
      Variant(size: "75 mm", rate: 295.0),
      Variant(size: "110 mm", rate: 551.0),
      Variant(size: "160 mm", rate: 1291.0),
    ],
  ),
  PriceListItem(
    itemName: 'Single Tee With Door',
    itemCode: 'UPVC106', // Changed from UPVC1006
    companyName: "Nepatop",
    category: "upvc",
    imageUrl: "assets/upvc/6.png",
    isCompanyItems: true,
    variants: [
      Variant(size: "75 mm", rate: 399.0),
      Variant(size: "110 mm", rate: 732.0),
      Variant(size: "160 mm", rate: 1815.0),
    ],
  ),
  PriceListItem(
    itemName: 'Cross Tee',
    itemCode: 'UPVC107', // Changed from UPVC1007
    companyName: "Nepatop",
    category: "upvc",
    imageUrl: "assets/upvc/7.png",
    isCompanyItems: true,
    variants: [
      Variant(size: "75 mm", rate: 744.0),
      Variant(size: "110 mm", rate: 1198.0),
      Variant(size: "160 mm", rate: 1914.0),
    ],
  ),
  PriceListItem(
    itemName: 'Reducer Y Tee 110x75',
    itemCode: 'UPVC108', // Changed from UPVC1008
    companyName: "Nepatop",
    category: "upvc",
    imageUrl: "assets/upvc/8.png",
    isCompanyItems: true,
    variants: [
      Variant(size: "110 mm", rate: 809.0),
    ],
  ),
  PriceListItem(
    itemName: 'Reducer Tee 160x110',
    itemCode: 'UPVC109', // Changed from UPVC1009
    companyName: "Nepatop",
    category: "upvc",
    imageUrl: "assets/upvc/9.png",
    isCompanyItems: true,
    variants: [
      Variant(size: "160 mm", rate: 1832.0),
    ],
  ),
  PriceListItem(
    itemName: 'Double Tee',
    itemCode: 'UPVC110', // Changed from UPVC1010
    companyName: "Nepatop",
    category: "upvc",
    imageUrl: "assets/upvc/10.png",
    isCompanyItems: true,
    variants: [
      Variant(size: "75 mm", rate: 637.0),
      Variant(size: "110 mm", rate: 1026.0),
    ],
  ),
  PriceListItem(
    itemName: 'Double Tee With Door',
    itemCode: 'UPVC111', // Changed from UPVC1011
    companyName: "Nepatop",
    category: "upvc",
    imageUrl: "assets/upvc/11.png",
    isCompanyItems: true,
    variants: [
      Variant(size: "75 mm", rate: 937.0),
      Variant(size: "110 mm", rate: 1479.0),
    ],
  ),
  PriceListItem(
    itemName: 'Pipe Clip',
    itemCode: 'UPVC112', // Changed from UPVC1012
    companyName: "Nepatop",
    category: "upvc",
    imageUrl: "assets/upvc/12.png",
    isCompanyItems: true,
    variants: [
      Variant(size: "50 mm", rate: 42.0),
      Variant(size: "75 mm", rate: 56.0),
      Variant(size: "110 mm", rate: 76.0),
      Variant(size: "160 mm", rate: 193.0),
    ],
  ),
  PriceListItem(
    itemName: 'Vent Cowell',
    itemCode: 'UPVC113', // Changed from UPVC1013
    companyName: "Nepatop",
    category: "upvc",
    imageUrl: "assets/upvc/13.png",
    isCompanyItems: true,
    variants: [
      Variant(size: "75 mm", rate: 81.0),
      Variant(size: "110 mm", rate: 133.0),
      Variant(size: "160 mm", rate: 394.0),
    ],
  ),
  PriceListItem(
    itemName: 'Socket Plug',
    itemCode: 'UPVC114', // Changed from UPVC1014
    companyName: "Nepatop",
    category: "upvc",
    imageUrl: "assets/upvc/14.png",
    isCompanyItems: true,
    variants: [
      Variant(size: "50 mm", rate: 68.0),
      Variant(size: "75 mm", rate: 148.0),
      Variant(size: "110 mm", rate: 224.0),
    ],
  ),
  PriceListItem(
    itemName: 'Single Y',
    itemCode: 'UPVC115', // Changed from UPVC1015
    companyName: "Nepatop",
    category: "upvc",
    imageUrl: "assets/upvc/15.png",
    isCompanyItems: true,
    variants: [
      Variant(size: "75 mm", rate: 400.0),
      Variant(size: "110 mm", rate: 736.0),
      Variant(size: "160 mm", rate: 3389.0),
    ],
  ),
  PriceListItem(
    itemName: 'Single Y With Door',
    itemCode: 'UPVC116', // Changed from UPVC1016
    companyName: "Nepatop",
    category: "upvc",
    imageUrl: "assets/upvc/16.png",
    isCompanyItems: true,
    variants: [
      Variant(size: "75 mm", rate: 465.0),
      Variant(size: "110 mm", rate: 883.0),
    ],
  ),
  PriceListItem(
    itemName: 'Double Y',
    itemCode: 'UPVC117', // Changed from UPVC1017
    companyName: "Nepatop",
    category: "upvc",
    imageUrl: "assets/upvc/17.png",
    isCompanyItems: true,
    variants: [
      Variant(size: "75 mm", rate: 1062.0),
      Variant(size: "110 mm", rate: 1376.0),
    ],
  ),
  PriceListItem(
    itemName: 'Double Y With Door',
    itemCode: 'UPVC118', // Changed from UPVC1018
    companyName: "Nepatop",
    category: "upvc",
    imageUrl: "assets/upvc/18.png",
    isCompanyItems: true,
    variants: [
      Variant(size: "75 mm", rate: 895.0),
      Variant(size: "110 mm", rate: 1371.0),
    ],
  ),
  PriceListItem(
    itemName: 'Cleaning Pipe',
    itemCode: 'UPVC119', // Changed from UPVC1019
    companyName: "Nepatop",
    category: "upvc",
    imageUrl: "assets/upvc/19.png",
    isCompanyItems: true,
    variants: [
      Variant(size: "75 mm", rate: 333.0),
      Variant(size: "110 mm", rate: 553.0),
    ],
  ),
  PriceListItem(
    itemName: 'Reducer Socket 110x75',
    itemCode: 'UPVC120', // Changed from UPVC1020
    companyName: "Nepatop",
    category: "upvc",
    imageUrl: "assets/upvc/20.png",
    isCompanyItems: true,
    variants: [
      Variant(size: "110 mm", rate: 268.0),
    ],
  ),
  PriceListItem(
    itemName: 'Reducer Socket 75x50',
    itemCode: 'UPVC121', // Changed from UPVC1021
    companyName: "Nepatop",
    category: "upvc",
    imageUrl: "assets/upvc/20.png",
    isCompanyItems: true,
    variants: [
      Variant(size: "75 mm", rate: 121.0),
    ],
  ),

  PriceListItem(
    itemName: 'Reducer Socket 160x110',
    itemCode: 'UPVC122', // Changed from UPVC1022
    companyName: "Nepatop",
    category: "upvc",
    imageUrl: "assets/upvc/20.png",
    isCompanyItems: true,
    variants: [
      Variant(size: "160 mm", rate: 502.0),
    ],
  ),
  PriceListItem(
    itemName: 'P Trap 125x110',
    itemCode: 'UPVC123', // Changed from UPVC1023
    companyName: "Nepatop",
    category: "upvc",
    imageUrl: "assets/upvc/23.png",
    isCompanyItems: true,
    variants: [
      Variant(size: "110 mm", rate: 982.0),
    ],
  ),
  PriceListItem(
    itemName: 'P Trap 110x110',
    itemCode: 'UPVC124', // Fixed from UPVC124 (already correct)
    companyName: "Nepatop",
    category: "upvc",
    imageUrl: "assets/upvc/23.png",
    isCompanyItems: true,
    variants: [
      Variant(size: "110 mm", rate: 1026.0),
    ],
  ),
  PriceListItem(
    itemName: 'P Trap 75x75',
    itemCode: 'UPVC125', // Fixed from UPVC125 (already correct)
    companyName: "Nepatop",
    category: "upvc",
    imageUrl: "assets/upvc/23.png",
    isCompanyItems: true,
    variants: [
      Variant(size: "75 mm", rate: 704.0),
    ],
  ),
  PriceListItem(
    itemName: 'Multi Floor Trap 110x75',
    itemCode: 'UPVC126', // Fixed from UPVC126 (already correct)
    companyName: "Nepatop",
    category: "upvc",
    imageUrl: "assets/upvc/26.png",
    isCompanyItems: true,
    variants: [
      Variant(size: "110 mm", rate: 793.0),
    ],
  ),
  PriceListItem(
    itemName: 'Multi Floor Trap 110x75 With Cap',
    itemCode: 'UPVC127', // Changed from UPVC1027
    companyName: "Nepatop",
    category: "upvc",
    imageUrl: "assets/upvc/26.png",
    isCompanyItems: true,
    variants: [
      Variant(size: "110 mm", rate: 829.0),
    ],
  ),
  PriceListItem(
    itemName: 'Nahani Trap 110x75',
    itemCode: 'UPVC128', // Changed from UPVC1028
    companyName: "Nepatop",
    category: "upvc",
    imageUrl: "assets/upvc/28.png",
    isCompanyItems: true,
    variants: [
      Variant(size: "110 mm", rate: 421.0),
    ],
  ),
  PriceListItem(
    itemName: 'W.C. Connector (Bent)',
    itemCode: 'UPVC129', // Changed from UPVC1029
    companyName: "Nepatop",
    category: "upvc",
    imageUrl: "assets/upvc/29.png",
    isCompanyItems: true,
    variants: [
      Variant(size: "110 mm", rate: 713.0),
    ],
  ),
  PriceListItem(
    itemName: 'Round Jali',
    itemCode: 'UPVC130', // Changed from UPVC1030
    companyName: "Nepatop",
    category: "upvc",
    imageUrl: "assets/upvc/30.png",
    isCompanyItems: true,
    variants: [
      Variant(size: "110 mm", rate: 64.0),
    ],
  ),
  PriceListItem(
    itemName: 'End Cap',
    itemCode: 'UPVC131', // Changed from UPVC1031
    companyName: "Nepatop",
    category: "upvc",
    imageUrl: "assets/upvc/31.png",
    isCompanyItems: true,
    variants: [
      Variant(size: "50 mm", rate: 49.0),
    ],
  ),
  PriceListItem(
    itemName: 'Square Tile Jali',
    itemCode: 'UPVC132', // Changed from UPVC1032
    companyName: "Nepatop",
    category: "upvc",
    imageUrl: "assets/upvc/32.png",
    isCompanyItems: true,
    variants: [
      Variant(size: "110 mm", rate: 227.0),
    ],
  ),
  PriceListItem(
    itemName: 'Multi Floor Trap Wall Nut',
    itemCode: 'UPVC133', // Changed from UPVC1033
    companyName: "Nepatop",
    category: "upvc",
    imageUrl: "assets/upvc/33.png",
    isCompanyItems: true,
    variants: [
      Variant(size: "110 mm", rate: 109.0),
    ],
  ),
  PriceListItem(
    itemName: 'Metal Clamp',
    itemCode: 'UPVC134', // Changed from UPVC1034
    companyName: "Nepatop",
    category: "upvc",
    imageUrl: "assets/upvc/34.png",
    isCompanyItems: true,
    variants: [
      Variant(size: "50 mm", rate: 50.0),
      Variant(size: "75 mm", rate: 67.0),
      Variant(size: "110 mm", rate: 81.0),
      Variant(size: "160 mm", rate: 167.0),
    ],
  ),

  // ------- -------------------cpvc ------------------------------------
  // CPVC Items (32 items)
  // CPVC Items (32 items)
  PriceListItem(
    itemName: 'CPVC Pipe SDR-11 (3-MTR)',
    itemCode: 'CPVC100',
    unit: "pic",
    companyName: "Nepatop",
    category: "cpvc",
    imageUrl: "assets/cpvc/1.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1/2"', rate: 535.0),
      Variant(size: '3/4"', rate: 815.0),
      Variant(size: '1"', rate: 1250.0),
      Variant(size: '1-1/4"', rate: 1780.0),
      Variant(size: '1-1/2"', rate: 2580.0),
      Variant(size: '2"', rate: 4145.0),
    ],
  ),
  PriceListItem(
    itemName: 'Socket',
    itemCode: 'CPVC101',
    companyName: "Nepatop",
    category: "cpvc",
    imageUrl: "assets/cpvc/2.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1/2"', rate: 16.0),
      Variant(size: '3/4"', rate: 27.0),
      Variant(size: '1"', rate: 50.0),
      Variant(size: '1-1/4"', rate: 95.0),
      Variant(size: '1-1/2"', rate: 160.0),
      Variant(size: '2"', rate: 331.0),
    ],
  ),
  PriceListItem(
    itemName: 'Pipe Clip',
    itemCode: 'CPVC102',
    companyName: "Nepatop",
    category: "cpvc",
    imageUrl: "assets/cpvc/3.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1/2"', rate: 14.0),
      Variant(size: '3/4"', rate: 15.0),
      Variant(size: '1"', rate: 17.0),
      Variant(size: '1-1/4"', rate: 24.0),
      Variant(size: '1-1/2"', rate: 34.0),
      Variant(size: '2"', rate: 42.0),
    ],
  ),
  PriceListItem(
    itemName: 'Elbow 90',
    itemCode: 'CPVC103',
    companyName: "Nepatop",
    category: "cpvc",
    imageUrl: "assets/cpvc/4.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1/2"', rate: 26.0),
      Variant(size: '3/4"', rate: 41.0),
      Variant(size: '1"', rate: 76.0),
      Variant(size: '1-1/4"', rate: 150.0),
      Variant(size: '1-1/2"', rate: 227.0),
      Variant(size: '2"', rate: 540.0),
    ],
  ),
  PriceListItem(
    itemName: 'Tee',
    itemCode: 'CPVC104',
    companyName: "Nepatop",
    category: "cpvc",
    imageUrl: "assets/cpvc/5.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1/2"', rate: 28.0),
      Variant(size: '3/4"', rate: 58.0),
      Variant(size: '1"', rate: 95.0),
      Variant(size: '1-1/4"', rate: 195.0),
      Variant(size: '1-1/2"', rate: 295.0),
      Variant(size: '2"', rate: 680.0),
    ],
  ),
  PriceListItem(
    itemName: 'Elbow 45°',
    itemCode: 'CPVC105',
    companyName: "Nepatop",
    category: "cpvc",
    imageUrl: "assets/cpvc/6.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1/2"', rate: 22.0),
      Variant(size: '3/4"', rate: 38.0),
      Variant(size: '1"', rate: 65.0),
      Variant(size: '1-1/4"', rate: 108.0),
      Variant(size: '1-1/2"', rate: 260.0),
      Variant(size: '2"', rate: 552.0),
    ],
  ),
  PriceListItem(
    itemName: 'Union',
    itemCode: 'CPVC106',
    companyName: "Nepatop",
    category: "cpvc",
    imageUrl: "assets/cpvc/7.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1/2"', rate: 175.0),
      Variant(size: '3/4"', rate: 260.0),
      Variant(size: '1"', rate: 314.0),
      Variant(size: '1-1/4"', rate: 493.0),
      Variant(size: '1-1/2"', rate: 660.0),
      Variant(size: '2"', rate: 1065.0),
    ],
  ),
  PriceListItem(
    itemName: 'End Cap',
    itemCode: 'CPVC107',
    companyName: "Nepatop",
    category: "cpvc",
    imageUrl: "assets/cpvc/8.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1/2"', rate: 18.0),
      Variant(size: '3/4"', rate: 30.0),
      Variant(size: '1"', rate: 44.0),
      Variant(size: '1-1/4"', rate: 72.0),
      Variant(size: '1-1/2"', rate: 109.0),
      Variant(size: '2"', rate: 201.0),
    ],
  ),
  PriceListItem(
    itemName: 'Cross Tee',
    itemCode: 'CPVC108',
    companyName: "Nepatop",
    category: "cpvc",
    imageUrl: "assets/cpvc/9.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1/2"', rate: 80.0),
      Variant(size: '3/4"', rate: 139.0),
      Variant(size: '1"', rate: 245.0),
    ],
  ),
  PriceListItem(
    itemName: 'Tank Nipple',
    itemCode: 'CPVC109',
    companyName: "Nepatop",
    category: "cpvc",
    imageUrl: "assets/cpvc/10.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '3/4"', rate: 207.0),
      Variant(size: '1"', rate: 230.0),
      Variant(size: '1-1/4"', rate: 415.0),
      Variant(size: '1-1/2"', rate: 596.0),
      Variant(size: '2"', rate: 912.0),
    ],
  ),
  PriceListItem(
    itemName: 'Female Threaded Adapter CPVC',
    itemCode: 'CPVC110',
    companyName: "Nepatop",
    category: "cpvc",
    imageUrl: "assets/cpvc/11.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1/2"', rate: 34.0),
      Variant(size: '3/4"', rate: 58.0),
      Variant(size: '1"', rate: 95.0),
      Variant(size: '1-1/4"', rate: 198.0),
      Variant(size: '1-1/2"', rate: 254.0),
      Variant(size: '2"', rate: 442.0),
    ],
  ),
  PriceListItem(
    itemName: 'CPVC Male Threaded Adapter',
    itemCode: 'CPVC111',
    companyName: "Nepatop",
    category: "cpvc",
    imageUrl: "assets/cpvc/12.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1/2"', rate: 25.0),
      Variant(size: '3/4" x 1/2"', rate: 45.0),
      Variant(size: '3/4" (20mm)', rate: 39.0),
      Variant(size: '1"', rate: 63.0),
      Variant(size: '1-1/4"', rate: 131.0),
      Variant(size: '1-1/2"', rate: 174.0),
      Variant(size: '2"', rate: 318.0),
    ],
  ),
  PriceListItem(
    itemName: 'Ball Valve',
    itemCode: 'CPVC112',
    companyName: "Nepatop",
    category: "cpvc",
    imageUrl: "assets/cpvc/13.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1/2"', rate: 275.0),
      Variant(size: '3/4"', rate: 467.0),
      Variant(size: '1"', rate: 760.0),
    ],
  ),
  PriceListItem(
    itemName: 'Heavy Ball Valve',
    itemCode: 'CPVC113',
    companyName: "Nepatop",
    category: "cpvc",
    imageUrl: "assets/cpvc/14.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1/2"', rate: 332.0),
      Variant(size: '3/4"', rate: 497.0),
      Variant(size: '1"', rate: 765.0),
      Variant(size: '1-1/4"', rate: 1410.0),
      Variant(size: '1-1/2"', rate: 2115.0),
      Variant(size: '2"', rate: 3350.0),
    ],
  ),
  PriceListItem(
    itemName: 'Cross Over',
    itemCode: 'CPVC114',
    companyName: "Nepatop",
    category: "cpvc",
    imageUrl: "assets/cpvc/15.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1/2"', rate: 169.0),
      Variant(size: '3/4"', rate: 205.0),
      Variant(size: '1"', rate: 518.0),
    ],
  ),
  PriceListItem(
    itemName: 'Plug',
    itemCode: 'CPVC115',
    companyName: "Nepatop",
    category: "cpvc",
    imageUrl: "assets/cpvc/16.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1/2"', rate: 17.0),
      Variant(size: '3/4"', rate: 19.0),
      Variant(size: '1"', rate: 43.0),
    ],
  ),
  PriceListItem(
    itemName: 'Tee Holder',
    itemCode: 'CPVC116',
    companyName: "Nepatop",
    category: "cpvc",
    imageUrl: "assets/cpvc/17.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1/2" x 1/2"', rate: 14.0),
      Variant(size: '3/4" x 1/2"', rate: 20.0),
    ],
  ),

  PriceListItem(
    itemName: 'Female Seated Elbow',
    itemCode: 'CPVC117',
    companyName: "Nepatop",
    category: "cpvc",
    imageUrl: "assets/cpvc/18.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1/2" x 1/2"', rate: 225.0),
      Variant(size: '3/4" x 1/2"', rate: 260.0),
    ],
  ),
  PriceListItem(
    itemName: 'Reducer Socket',
    itemCode: 'CPVC118',
    companyName: "Nepatop",
    category: "cpvc",
    imageUrl: "assets/cpvc/19.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '3/4" x 1/2"', rate: 35.0),
      Variant(size: '1" x 1/2"', rate: 48.0),
      Variant(size: '1" x 3/4"', rate: 51.0),
      Variant(size: '1-1/4" x 1/2"', rate: 156.0),
      Variant(size: '1-1/4" x 3/4"', rate: 160.0),
      Variant(size: '1-1/4" x 1"', rate: 168.0),
      Variant(size: '1-1/2" x 1/2"', rate: 278.0),
      Variant(size: '1-1/2" x 3/4"', rate: 284.0),
      Variant(size: '1-1/2" x 1"', rate: 260.0),
      Variant(size: '1-1/2" x 1-1/4"', rate: 304.0),
      Variant(size: '2" x 3/4"', rate: 470.0),
      Variant(size: '2" x 1"', rate: 485.0),
      Variant(size: '2" x 1-1/4"', rate: 502.0),
      Variant(size: '2" x 1-1/2"', rate: 510.0),
    ],
  ),
  PriceListItem(
    itemName: 'Reducer Tee',
    itemCode: 'CPVC119',
    companyName: "Nepatop",
    category: "cpvc",
    imageUrl: "assets/cpvc/20.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '3/4" x 1/2"', rate: 68.0),
      Variant(size: '1" x 1/2"', rate: 98.0),
      Variant(size: '1" x 3/4"', rate: 105.0),
      Variant(size: '1-1/4" x 1/2"', rate: 158.0),
      Variant(size: '1-1/4" x 3/4"', rate: 162.0),
      Variant(size: '1-1/4" x 1"', rate: 173.0),
      Variant(size: '1-1/2" x 1/2"', rate: 285.0),
      Variant(size: '1-1/2" x 3/4"', rate: 288.0),
      Variant(size: '1-1/2" x 1"', rate: 256.0),
      Variant(size: '1-1/2" x 1-1/4"', rate: 310.0),
      Variant(size: '2" x 3/4"', rate: 470.0),
      Variant(size: '2" x 1"', rate: 485.0),
      Variant(size: '2" x 1-1/4"', rate: 495.0),
      Variant(size: '2" x 1-1/2"', rate: 606.0),
    ],
  ),
  PriceListItem(
    itemName: 'Reducing Bush',
    itemCode: 'CPVC120',
    companyName: "Nepatop",
    category: "cpvc",
    imageUrl: "assets/cpvc/21.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '3/4" x 1/2"', rate: 18.0),
      Variant(size: '1" x 1/2"', rate: 37.0),
      Variant(size: '1" x 3/4"', rate: 40.0),
      Variant(size: '1-1/4" x 1/2"', rate: 92.0),
      Variant(size: '1-1/4" x 3/4"', rate: 78.0),
      Variant(size: '1-1/4" x 1"', rate: 71.0),
      Variant(size: '1-1/2" x 1/2"', rate: 118.0),
      Variant(size: '1-1/2" x 3/4"', rate: 109.0),
      Variant(size: '1-1/2" x 1"', rate: 121.0),
      Variant(size: '1-1/2" x 1-1/4"', rate: 107.0),
      Variant(size: '2" x 1/2"', rate: 268.0),
      Variant(size: '2" x 3/4"', rate: 272.0),
      Variant(size: '2" x 1"', rate: 277.0),
      Variant(size: '2" x 1-1/4"', rate: 299.0),
      Variant(size: '2" x 1-1/2"', rate: 278.0),
    ],
  ),
  PriceListItem(
    itemName: 'Female Elbow',
    itemCode: 'CPVC121',
    companyName: "Nepatop",
    category: "cpvc",
    imageUrl: "assets/cpvc/22.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1/2" x 1/2"', rate: 168.0),
      Variant(size: '3/4" x 1/2"', rate: 155.0),
      Variant(size: '3/4" x 3/4"', rate: 216.0),
      Variant(size: '1" x 1/2"', rate: 252.0),
      Variant(size: '1" x 1"', rate: 670.0),
    ],
  ),
  PriceListItem(
    itemName: 'Female Tee',
    itemCode: 'CPVC122',
    companyName: "Nepatop",
    category: "cpvc",
    imageUrl: "assets/cpvc/23.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1/2" x 1/2"', rate: 172.0),
      Variant(size: '3/4" x 1/2"', rate: 180.0),
      Variant(size: '3/4" x 3/4"', rate: 255.0),
      Variant(size: '1" x 1/2"', rate: 265.0),
      Variant(size: '1" x 1"', rate: 695.0),
    ],
  ),
  PriceListItem(
    itemName: 'Female Socket',
    itemCode: 'CPVC123',
    companyName: "Nepatop",
    category: "cpvc",
    imageUrl: "assets/cpvc/24.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1/2" x 1/2"', rate: 220.0),
      Variant(size: '3/4" x 1/2"', rate: 222.0),
      Variant(size: '3/4" x 3/4"', rate: 290.0),
      Variant(size: '1" x 1/2"', rate: 245.0),
      Variant(size: '1" x 1"', rate: 315.0),
    ],
  ),
  PriceListItem(
    itemName: 'Reducer Elbow',
    itemCode: 'CPVC124',
    companyName: "Nepatop",
    category: "cpvc",
    imageUrl: "assets/cpvc/25.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '3/4" x 1/2"', rate: 54.0),
      Variant(size: '1" x 3/4"', rate: 96.0),
      Variant(size: '1" x 1/2"', rate: 90.0),
    ],
  ),
  PriceListItem(
    itemName: 'Male Socket',
    itemCode: 'CPVC125',
    companyName: "Nepatop",
    category: "cpvc",
    imageUrl: "assets/cpvc/26.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1/2" x 1/2"', rate: 234.0),
      Variant(size: '3/4" x 1/2"', rate: 275.0),
      Variant(size: '3/4" x 3/4"', rate: 327.0),
      Variant(size: '1" x 1"', rate: 580.0),
    ],
  ),
  PriceListItem(
    itemName: 'Brass Threaded Female Adaptor ',
    itemCode: 'CPVC126',
    companyName: "Nepatop",
    category: "cpvc",
    imageUrl: "assets/cpvc/27.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1/2"', rate: 270.0),
      Variant(size: '3/4"', rate: 415.0),
      Variant(size: '1"', rate: 727.0),
      Variant(size: '1-1/4"', rate: 1530.0),
      Variant(size: '1-1/2"', rate: 1795.0),
      Variant(size: '2"', rate: 2850.0),
    ],
  ),
  PriceListItem(
    itemName: 'Brass Threaded Male Adaptor',
    itemCode: 'CPVC127',
    companyName: "Nepatop",
    category: "cpvc",
    imageUrl: "assets/cpvc/28.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1/2"', rate: 282.0),
      Variant(size: '3/4"', rate: 402.0),
      Variant(size: '1"', rate: 695.0),
      Variant(size: '1"x1/2"', rate: 695.0),
      Variant(size: '1-1/4"', rate: 1555.0),
      Variant(size: '1-1/2"', rate: 1955.0),
      Variant(size: '2"', rate: 3430.0),
    ],
  ),
  PriceListItem(
    itemName: 'Triple Female Elbow',
    itemCode: 'CPVC128',
    companyName: "Nepatop",
    category: "cpvc",
    imageUrl: "assets/cpvc/29.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1/2" x 1/2"', rate: 941.0),
    ],
  ),
  PriceListItem(
    itemName: 'Double Female Elbow',
    itemCode: 'CPVC129',
    companyName: "Nepatop",
    category: "cpvc",
    imageUrl: "assets/cpvc/30.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1/2" x 1/2"', rate: 655.0),
    ],
  ),
  PriceListItem(
    itemName: 'Metal Pipe Clip',
    itemCode: 'CPVC130',
    companyName: "Nepatop",
    category: "cpvc",
    imageUrl: "assets/cpvc/31.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1/2"', rate: 18.0),
      Variant(size: '3/4"', rate: 18.0),
      Variant(size: '1"', rate: 24.0),
      Variant(size: '1-1/4"', rate: 30.0),
      Variant(size: '1-1/2"', rate: 36.0),
      Variant(size: '2"', rate: 46.0),
    ],
  ),
  PriceListItem(
    itemName: 'Long Plug',
    itemCode: 'CPVC131',
    companyName: "Nepatop",
    category: "cpvc",
    imageUrl: "assets/cpvc/32.png",
    isCompanyItems: true,
    variants: [
      Variant(size: '1/2"', rate: 25.0),
      Variant(size: '3/4"', rate: 37.0),
    ],
  ),
  PriceListItem(
    itemName: 'CPVC Solvent Cement',
    itemCode: 'CPVC132',
    companyName: "Nepatop",
    category: "additional_items",
    imageUrl: "assets/upvc/solvent.jpg",
    unit: "pic",
    isCompanyItems: false,
    variants: [
      Variant(size: '100 ml', rate: 286.0),
      Variant(size: '200 ml', rate: 538.0),
      Variant(size: '1000 ml', rate: 1791.0),
    ],
  ),
];
